/* ============================================================
   Placement readiness report (PDF)
   ------------------------------------------------------------
   CSV is for analysts. A TPO's actual deliverable is a document
   they forward to the director and file against accreditation
   criteria (NAAC 5.2 / NBA), where the required evidence is
   placement percentage, package figures and the recruiter list.

   Built with vector text via jsPDF — not a screenshot. That keeps
   the file small, the text selectable and searchable, and the
   numbers copy-pasteable into whatever return the college is
   filling in.

   Every figure is passed in from the deterministic placement and
   observability engines. This module formats; it never computes a
   statistic of its own, so the PDF can never disagree with the
   dashboard it was printed from.
   ============================================================ */

const MARGIN = 48;
const LINE = 14;

/* Aurora-ish palette, flattened for print legibility on white paper. */
const INK = [17, 24, 39];
const MUTED = [107, 114, 128];
const RULE = [209, 213, 219];
const ACCENT = [79, 70, 229];

function fmtDate(d = new Date()) {
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

/** ₹ LPA is the only package unit an Indian placement report uses. */
function lpa(n) {
  const v = Number(n);
  if (!Number.isFinite(v) || v <= 0) return '—';
  return `${v.toFixed(2)} LPA`;
}

export async function exportCollegeReportPDF({
  collegeName = 'Placement report',
  placement = {},
  observability = {},
  fileName = 'placement-readiness-report.pdf',
} = {}) {
  const { default: jsPDF } = await import('jspdf');
  const pdf = new jsPDF({ unit: 'pt', format: 'a4', compress: true });
  const W = pdf.internal.pageSize.getWidth();
  const H = pdf.internal.pageSize.getHeight();
  let y = MARGIN;

  const setColor = (c) => pdf.setTextColor(c[0], c[1], c[2]);

  /* Page breaks are checked before every block rather than after, so a
     heading can never be orphaned at the foot of a page. */
  const need = (space) => {
    if (y + space > H - MARGIN - 24) {
      footer();
      pdf.addPage();
      y = MARGIN;
      return true;
    }
    return false;
  };

  let pageNo = 0;
  const footer = () => {
    pageNo++;
    pdf.setFontSize(8);
    setColor(MUTED);
    pdf.text('Generated by Career Autopilot · figures are rule-based and reproducible', MARGIN, H - 28);
    pdf.text(String(pageNo), W - MARGIN, H - 28, { align: 'right' });
  };

  const heading = (text) => {
    need(40);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    setColor(INK);
    pdf.text(text, MARGIN, y);
    y += 8;
    pdf.setDrawColor(RULE[0], RULE[1], RULE[2]);
    pdf.line(MARGIN, y, W - MARGIN, y);
    y += 16;
  };

  const para = (text, { size = 9, color = MUTED } = {}) => {
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(size);
    setColor(color);
    const lines = pdf.splitTextToSize(String(text), W - MARGIN * 2);
    for (const ln of lines) {
      need(LINE);
      pdf.text(ln, MARGIN, y);
      y += LINE;
    }
  };

  /* ---- Title block ---- */
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(20);
  setColor(INK);
  pdf.text('Placement Readiness Report', MARGIN, y);
  y += 24;
  pdf.setFontSize(12);
  setColor(ACCENT);
  pdf.text(String(collegeName), MARGIN, y);
  y += 16;
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(9);
  setColor(MUTED);
  pdf.text(`Generated ${fmtDate()}`, MARGIN, y);
  y += 22;

  const s = placement.summary || {};
  const k = observability.kpis || {};

  /* ---- Headline metric grid ---- */
  const cards = [
    ['Students on record', String(s.students ?? 0)],
    ['Placed (offer accepted)', String(s.placed ?? 0)],
    ['Placement rate', `${s.placementRate ?? 0}%`],
    ['Offers made', String(s.offers ?? 0)],
    ['Median package', lpa(s.medianCtc)],
    ['Highest package', lpa(s.highestCtc)],
    ['Average package', lpa(s.avgCtc)],
    ['Recruiters engaged', String(s.recruiters ?? 0)],
  ];

  const COLS = 4;
  const cw = (W - MARGIN * 2) / COLS;
  const chh = 46;
  need(chh * Math.ceil(cards.length / COLS) + 10);
  cards.forEach(([label, value], i) => {
    const col = i % COLS;
    const row = Math.floor(i / COLS);
    const cx = MARGIN + col * cw;
    const cy = y + row * chh;
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(7.5);
    setColor(MUTED);
    pdf.text(String(label).toUpperCase(), cx, cy);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(15);
    setColor(INK);
    pdf.text(String(value), cx, cy + 18);
  });
  y += chh * Math.ceil(cards.length / COLS) + 8;

  /* Honest caveat: a median computed over partial data must say so, or the
     figure gets quoted as if it covered every placement. */
  if (s.placed > 0 && (s.ctcCoverage ?? 100) < 100) {
    para(
      `Package figures cover ${s.ctcCoverage}% of placements (${s.offersWithoutCtc} accepted offer(s) have no CTC recorded). `
      + 'Median, average and highest are computed only over placements with a recorded package.'
    );
    y += 4;
  }

  /* ---- Readiness pipeline ---- */
  heading('Readiness pipeline');
  para(
    `Average readiness ${k.avgReadiness ?? 0}/100 · average resume score ${k.avgResume ?? 0}/100 · `
    + `${k.recruiterReady ?? 0} students recruiter-ready · ${k.verifiedStudents ?? 0} with verified proof of work · `
    + `${k.atRisk ?? 0} flagged at risk.`
  );
  y += 6;

  const funnel = observability.funnel || [];
  if (funnel.length) {
    const maxCount = Math.max(...funnel.map((f) => Number(f.count) || 0), 1);
    for (const stage of funnel) {
      need(20);
      const barW = (W - MARGIN * 2 - 180) * ((Number(stage.count) || 0) / maxCount);
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      setColor(INK);
      pdf.text(String(stage.label || stage.id || ''), MARGIN, y + 8);
      pdf.setFillColor(ACCENT[0], ACCENT[1], ACCENT[2]);
      pdf.rect(MARGIN + 150, y, Math.max(1, barW), 9, 'F');
      setColor(MUTED);
      pdf.text(String(stage.count ?? 0), W - MARGIN, y + 8, { align: 'right' });
      y += 18;
    }
    y += 6;
  }

  /* ---- Table helper ---- */
  const mkTable = (columns, rows) => {
    const weights = columns.map((c) => c.width || 1);
    const total = weights.reduce((a, b) => a + b, 0);
    const widths = weights.map((v) => ((W - MARGIN * 2) * v) / total);
    const xs = [];
    let acc = MARGIN;
    for (const w of widths) { xs.push(acc); acc += w; }

    need(30);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(8);
    setColor(MUTED);
    columns.forEach((c, i) => {
      const x = c.align === 'right' ? xs[i] + widths[i] - 4 : xs[i];
      pdf.text(String(c.header).toUpperCase(), x, y, { align: c.align === 'right' ? 'right' : 'left' });
    });
    y += 6;
    pdf.setDrawColor(RULE[0], RULE[1], RULE[2]);
    pdf.line(MARGIN, y, W - MARGIN, y);
    y += 13;

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(9);
    for (const r of rows) {
      need(LINE + 2);
      setColor(INK);
      columns.forEach((c, i) => {
        const raw = String(c.value(r) ?? '');
        const txt = raw.length > 40 ? `${raw.slice(0, 39)}…` : raw;
        const x = c.align === 'right' ? xs[i] + widths[i] - 4 : xs[i];
        pdf.text(txt, x, y, { align: c.align === 'right' ? 'right' : 'left' });
      });
      y += LINE + 2;
    }
    y += 10;
  };
  /* ---- Branch-wise ---- */
  const byBranch = placement.byBranch || [];
  if (byBranch.length) {
    heading('Branch-wise placement');
    mkTable([
      { header: 'Branch', value: (r) => r.key, width: 2 },
      { header: 'Students', value: (r) => r.total, width: 1, align: 'right' },
      { header: 'Placed', value: (r) => r.placed, width: 1, align: 'right' },
      { header: 'Rate', value: (r) => `${r.placementRate}%`, width: 1, align: 'right' },
      { header: 'Median', value: (r) => lpa(r.medianCtc), width: 1.4, align: 'right' },
      { header: 'Highest', value: (r) => lpa(r.highestCtc), width: 1.4, align: 'right' },
    ], byBranch);
  }

  /* ---- Batch comparison ---- */
  const batches = placement.batchComparison || [];
  if (batches.length) {
    heading('Batch comparison');
    mkTable([
      { header: 'Batch', value: (r) => r.batch, width: 1.2 },
      { header: 'Students', value: (r) => r.students, width: 1, align: 'right' },
      { header: 'Avg readiness', value: (r) => r.avgReadiness, width: 1.3, align: 'right' },
      { header: 'Verified %', value: (r) => `${r.verifiedCoverage}%`, width: 1.2, align: 'right' },
      { header: 'Ready %', value: (r) => `${r.placementReadyRate}%`, width: 1.1, align: 'right' },
      { header: 'Placed %', value: (r) => `${r.placementRate}%`, width: 1.1, align: 'right' },
    ], batches);
  }

  /* ---- Recruiters ---- */
  const recruiters = placement.topRecruiters || [];
  if (recruiters.length) {
    heading('Recruiters');
    mkTable([
      { header: 'Company', value: (r) => r.company, width: 3 },
      { header: 'Hires', value: (r) => r.hires, width: 1, align: 'right' },
      { header: 'Median', value: (r) => lpa(r.medianCtc), width: 1.4, align: 'right' },
      { header: 'Highest', value: (r) => lpa(r.highestCtc), width: 1.4, align: 'right' },
    ], recruiters);
  }

  /* ---- The action list ---- */
  const ready = placement.readyUnplaced || [];
  if (ready.length) {
    heading('Ready but not yet placed');
    para(
      `${ready.length} student(s) score 70+ on readiness and have not accepted an offer. `
      + 'This is the highest-yield intervention list in the report — they are prepared and available.'
    );
    y += 4;
    mkTable([
      { header: 'Student', value: (r) => r.name || r.email, width: 2.6 },
      { header: 'Branch', value: (r) => r.branch || '—', width: 1.2 },
      { header: 'Batch', value: (r) => r.batch || '—', width: 1 },
      { header: 'Readiness', value: (r) => r.readinessScore, width: 1.1, align: 'right' },
      { header: 'Applications', value: (r) => r.applications, width: 1.2, align: 'right' },
    ], ready.slice(0, 40));
    if (ready.length > 40) para(`… and ${ready.length - 40} more. The full list is in the observability CSV export.`);
  }

  /* ---- Methodology, so no number in here is a black box ---- */
  heading('How these figures are produced');
  para(
    'Placement rate counts students who ACCEPTED an offer, divided by all students on record. '
    + 'An outstanding offer is not counted as a placement. Package statistics are computed only over accepted '
    + 'offers with a recorded CTC; missing figures are excluded rather than treated as zero. Readiness is a '
    + 'deterministic score derived from verified projects, verified skill XP and resume quality — no AI model '
    + 'contributes to any score, stage or flag in this report, and re-running it on the same data yields '
    + 'identical output.'
  );

  footer();
  pdf.save(fileName);
  return { ok: true, fileName, pages: pageNo };
}

export default { exportCollegeReportPDF };
