/* ============================================================
   ARCHITECTURE KNOWLEDGE BASE  (curated, offline, deterministic)
   ------------------------------------------------------------
   No internet access required. Three datasets:
     1. CAPABILITY_CATALOG  — every generic capability the engine knows,
        with layer, icon key, node type and default technologies.
     2. CLOUD_SERVICES      — capability → AWS / Azure / GCP / generic name.
     3. ARCHITECTURE_PATTERNS — curated reference architectures.
     4. DIAGRAM_TEMPLATES   — per-view defaults (groups, layout hints).
   Everything here is data only — no logic. The pattern matcher,
   service mapper and spec builder consume it.
   ============================================================ */

export const KB_VERSION = 'arch-kb-v1';

/* ---- 1. Capability catalog ----
   layer: edge | app | data | async | observability | security | cicd | external | actor
   nodeType: actor | external | service | datastore | queue | pipeline | security | monitor */
export const CAPABILITY_CATALOG = {
  user:             { label: 'End User',            layer: 'actor',        icon: 'user',          nodeType: 'actor' },
  adminUser:        { label: 'Admin',               layer: 'actor',        icon: 'user',          nodeType: 'actor' },
  externalSystem:   { label: 'External System',     layer: 'external',     icon: 'externalSystem', nodeType: 'external' },
  dns:              { label: 'DNS',                 layer: 'edge',         icon: 'globe',         nodeType: 'service' },
  cdn:              { label: 'CDN',                 layer: 'edge',         icon: 'globe',         nodeType: 'service' },
  waf:              { label: 'WAF',                 layer: 'edge',         icon: 'shield',        nodeType: 'security' },
  loadBalancer:     { label: 'Load Balancer',       layer: 'edge',         icon: 'network',       nodeType: 'service' },
  apiGateway:       { label: 'API Gateway',         layer: 'edge',         icon: 'network',       nodeType: 'service' },
  frontend:         { label: 'Web Frontend (SPA)',  layer: 'app',          icon: 'monitor',       nodeType: 'service', technologies: ['React', 'Vite'] },
  backend:          { label: 'API / App Service',   layer: 'app',          icon: 'server',        nodeType: 'service', technologies: ['Node.js', 'Express'] },
  authService:      { label: 'Auth / Identity',     layer: 'security',     icon: 'key',           nodeType: 'security' },
  rbac:             { label: 'Authorization (RBAC)', layer: 'security',    icon: 'shield',        nodeType: 'security' },
  rateLimiter:      { label: 'Rate Limiting',       layer: 'security',     icon: 'gauge',         nodeType: 'security' },
  secrets:          { label: 'Secrets Manager',     layer: 'security',     icon: 'key',           nodeType: 'security' },
  auditLog:         { label: 'Audit Log',           layer: 'security',     icon: 'fileText',      nodeType: 'datastore' },
  computeContainer: { label: 'Container Runtime',   layer: 'app',          icon: 'container',     nodeType: 'service' },
  serverlessFn:     { label: 'Serverless Functions', layer: 'app',         icon: 'zap',           nodeType: 'service' },
  worker:           { label: 'Background Worker',   layer: 'async',        icon: 'cpu',           nodeType: 'service' },
  scheduler:        { label: 'Scheduler / Cron',    layer: 'async',        icon: 'clock',         nodeType: 'service' },
  queue:            { label: 'Message Queue',       layer: 'async',        icon: 'list',          nodeType: 'queue' },
  eventBus:         { label: 'Event Bus',           layer: 'async',        icon: 'workflow',      nodeType: 'queue' },
  dlq:              { label: 'Dead-letter Queue',   layer: 'async',        icon: 'list',          nodeType: 'queue' },
  relationalDb:     { label: 'Relational DB',       layer: 'data',         icon: 'database',      nodeType: 'datastore', technologies: ['PostgreSQL'] },
  documentDb:       { label: 'Document DB',         layer: 'data',         icon: 'database',      nodeType: 'datastore', technologies: ['MongoDB'] },
  cache:            { label: 'Cache',               layer: 'data',         icon: 'zap',           nodeType: 'datastore', technologies: ['Redis'] },
  search:           { label: 'Search Index',        layer: 'data',         icon: 'search',        nodeType: 'datastore' },
  vectorDb:         { label: 'Vector Store',        layer: 'data',         icon: 'brain',         nodeType: 'datastore' },
  objectStorage:    { label: 'Object Storage',      layer: 'data',         icon: 'archive',       nodeType: 'datastore' },
  dataWarehouse:    { label: 'Data Warehouse',      layer: 'data',         icon: 'database',      nodeType: 'datastore' },
  streamProcessor:  { label: 'Stream Processor',    layer: 'async',        icon: 'workflow',      nodeType: 'service' },
  ai:               { label: 'AI / LLM Service',    layer: 'app',          icon: 'brain',         nodeType: 'service' },
  embedding:        { label: 'Embedding Service',   layer: 'app',          icon: 'brain',         nodeType: 'service' },
  payments:         { label: 'Payments Provider',   layer: 'external',     icon: 'creditCard',    nodeType: 'external' },
  notifications:    { label: 'Notifications',       layer: 'async',        icon: 'bell',          nodeType: 'service' },
  monitoring:       { label: 'Monitoring / Metrics', layer: 'observability', icon: 'activity',    nodeType: 'monitor' },
  logging:          { label: 'Centralized Logs',    layer: 'observability', icon: 'fileText',     nodeType: 'monitor' },
  tracing:          { label: 'Distributed Tracing', layer: 'observability', icon: 'route',        nodeType: 'monitor' },
  alerting:         { label: 'Alerting',            layer: 'observability', icon: 'bell',         nodeType: 'monitor' },
  dashboard:        { label: 'Dashboards',          layer: 'observability', icon: 'gauge',        nodeType: 'monitor' },
  cicdPipeline:     { label: 'CI/CD Pipeline',      layer: 'cicd',         icon: 'gitBranch',     nodeType: 'pipeline' },
  sourceRepo:       { label: 'Git Repository',      layer: 'cicd',         icon: 'gitBranch',     nodeType: 'pipeline' },
  registry:         { label: 'Container Registry',  layer: 'cicd',         icon: 'box',           nodeType: 'pipeline' },
  iac:              { label: 'Infrastructure as Code', layer: 'cicd',      icon: 'fileText',      nodeType: 'pipeline' },
  backup:           { label: 'Backup & Restore',    layer: 'data',         icon: 'archive',       nodeType: 'datastore' },
  decisionEngine:   { label: 'Decision Engine',     layer: 'app',          icon: 'brain',         nodeType: 'service' },
  ingestion:        { label: 'Ingestion Service',   layer: 'app',          icon: 'workflow',      nodeType: 'service' },
};

/* ---- 2. Cloud service mappings (capability → provider service name) ---- */
export const CLOUD_SERVICES = {
  dns:              { aws: 'Route 53',            azure: 'Azure DNS',                 gcp: 'Cloud DNS',            generic: 'DNS' },
  cdn:              { aws: 'CloudFront',          azure: 'Azure Front Door',          gcp: 'Cloud CDN',            generic: 'CDN' },
  waf:              { aws: 'AWS WAF',             azure: 'Azure WAF',                 gcp: 'Cloud Armor',          generic: 'WAF' },
  loadBalancer:     { aws: 'ALB / ELB',           azure: 'Azure Load Balancer',       gcp: 'Cloud Load Balancing', generic: 'Load Balancer' },
  apiGateway:       { aws: 'API Gateway',         azure: 'API Management',            gcp: 'API Gateway',          generic: 'API Gateway' },
  computeContainer: { aws: 'ECS / EKS',           azure: 'AKS / Container Apps',      gcp: 'GKE / Cloud Run',      generic: 'Container Runtime' },
  serverlessFn:     { aws: 'Lambda',              azure: 'Azure Functions',           gcp: 'Cloud Functions',      generic: 'Serverless Functions' },
  queue:            { aws: 'SQS',                 azure: 'Service Bus',               gcp: 'Pub/Sub',              generic: 'Message Queue' },
  eventBus:         { aws: 'EventBridge / SNS',   azure: 'Event Grid',                gcp: 'Pub/Sub',              generic: 'Event Bus' },
  dlq:              { aws: 'SQS DLQ',             azure: 'Service Bus DLQ',           gcp: 'Pub/Sub dead-letter',  generic: 'Dead-letter Queue' },
  objectStorage:    { aws: 'S3',                  azure: 'Blob Storage',              gcp: 'Cloud Storage',        generic: 'Object Storage' },
  secrets:          { aws: 'Secrets Manager',     azure: 'Key Vault',                 gcp: 'Secret Manager',       generic: 'Secrets Vault' },
  monitoring:       { aws: 'CloudWatch',          azure: 'Azure Monitor',             gcp: 'Cloud Monitoring',     generic: 'Monitoring' },
  logging:          { aws: 'CloudWatch Logs',     azure: 'Log Analytics',             gcp: 'Cloud Logging',        generic: 'Centralized Logs' },
  tracing:          { aws: 'X-Ray',               azure: 'Application Insights',      gcp: 'Cloud Trace',          generic: 'Tracing' },
  alerting:         { aws: 'CloudWatch Alarms',   azure: 'Azure Alerts',              gcp: 'Cloud Alerting',       generic: 'Alerting' },
  documentDb:       { aws: 'DocumentDB / MongoDB Atlas', azure: 'Cosmos DB',          gcp: 'Firestore',            generic: 'Document DB' },
  relationalDb:     { aws: 'RDS',                 azure: 'Azure SQL',                 gcp: 'Cloud SQL',            generic: 'Relational DB' },
  cache:            { aws: 'ElastiCache (Redis)', azure: 'Azure Cache for Redis',     gcp: 'Memorystore',          generic: 'Redis Cache' },
  search:           { aws: 'OpenSearch',          azure: 'Azure AI Search',           gcp: 'Vertex AI Search',     generic: 'Search Index' },
  vectorDb:         { aws: 'OpenSearch k-NN / pgvector', azure: 'Cosmos DB vector',   gcp: 'Vertex Vector Search', generic: 'Vector Store' },
  dataWarehouse:    { aws: 'Redshift',            azure: 'Synapse',                   gcp: 'BigQuery',             generic: 'Data Warehouse' },
  streamProcessor:  { aws: 'Kinesis / MSK',       azure: 'Event Hubs',                gcp: 'Dataflow',             generic: 'Stream Processor' },
  cicdPipeline:     { aws: 'CodePipeline / GitHub Actions', azure: 'Azure DevOps',    gcp: 'Cloud Build',          generic: 'CI/CD Pipeline' },
  registry:         { aws: 'ECR',                 azure: 'ACR',                       gcp: 'Artifact Registry',    generic: 'Container Registry' },
  iac:              { aws: 'Terraform / CDK',     azure: 'Terraform / Bicep',         gcp: 'Terraform',            generic: 'IaC' },
  backup:           { aws: 'AWS Backup',          azure: 'Azure Backup',              gcp: 'Backup and DR',        generic: 'Backup' },
  monitoringDash:   { aws: 'CloudWatch Dashboards', azure: 'Azure Dashboards',        gcp: 'Cloud Monitoring',     generic: 'Dashboards' },
};

/* ---- 3. Architecture patterns ---- */
const BASE_SECURITY = ['TLS everywhere', 'AuthN + AuthZ on every protected route', 'Input validation at the boundary', 'Secrets in a vault, never in code', 'Rate limiting at the edge'];
const BASE_SCALE = ['Stateless app instances behind a load balancer', 'Cache hot reads', 'Async queue for slow work', 'Read replicas before sharding'];
const BASE_OBS = ['Structured logs with request IDs', 'Metrics + dashboards', 'Alerting on SLO breaches'];

export const ARCHITECTURE_PATTERNS = [
  {
    id: 'three-tier-saas',
    name: 'Three-tier SaaS web app',
    category: 'web',
    useCases: ['SaaS product', 'CRUD web app', 'dashboard product', 'B2B portal'],
    keywords: ['saas', 'web app', 'dashboard', 'portal', 'crud', 'fullstack', 'full stack', 'react', 'express'],
    requiredCapabilities: ['user', 'cdn', 'frontend', 'backend', 'authService', 'relationalDb', 'cache', 'objectStorage', 'monitoring', 'cicdPipeline', 'secrets', 'rateLimiter', 'backup'],
    recommendedComponents: ['waf', 'queue', 'worker', 'logging', 'alerting'],
    recommendedViews: ['systemContext', 'container', 'deployment', 'dataFlow', 'security', 'cicd', 'observability', 'scalingFailure'],
    commonFlows: ['User → CDN → Frontend → API → DB', 'API → Cache → DB fallback', 'API → Queue → Worker for slow jobs'],
    securityControls: BASE_SECURITY,
    scalabilityControls: BASE_SCALE,
    observabilityControls: BASE_OBS,
    commonAntiPatterns: ['Premature microservices', 'Business logic in the frontend', 'DB credentials in env files committed to git'],
    cloudProviderMappings: { compute: 'computeContainer', db: 'relationalDb' },
  },
  {
    id: 'microservices-saas',
    name: 'Microservices SaaS platform',
    category: 'web',
    useCases: ['large multi-team SaaS', 'independently deployed domains', 'high-scale platform'],
    keywords: ['microservice', 'microservices', 'kubernetes', 'k8s', 'service mesh', 'grpc', 'distributed'],
    requiredCapabilities: ['user', 'cdn', 'waf', 'apiGateway', 'frontend', 'backend', 'authService', 'eventBus', 'queue', 'worker', 'relationalDb', 'cache', 'objectStorage', 'monitoring', 'tracing', 'cicdPipeline', 'registry', 'secrets', 'rateLimiter', 'backup'],
    recommendedComponents: ['search', 'dlq', 'iac', 'logging', 'alerting'],
    recommendedViews: ['systemContext', 'container', 'deployment', 'dataFlow', 'security', 'cicd', 'observability', 'scalingFailure'],
    commonFlows: ['Client → API Gateway → service', 'Service → Event Bus → consumers', 'Per-service datastore ownership'],
    securityControls: [...BASE_SECURITY, 'mTLS / service-to-service auth', 'Per-service least-privilege IAM'],
    scalabilityControls: [...BASE_SCALE, 'Independent horizontal scaling per service', 'Backpressure via queues'],
    observabilityControls: [...BASE_OBS, 'Distributed tracing across all services'],
    commonAntiPatterns: ['Distributed monolith (sync chains everywhere)', 'Shared database across services', 'No tracing'],
    cloudProviderMappings: { compute: 'computeContainer', db: 'relationalDb' },
  },
  {
    id: 'ai-rag-platform',
    name: 'AI / RAG platform',
    category: 'ai',
    useCases: ['LLM product', 'retrieval-augmented generation', 'AI assistant', 'document Q&A'],
    keywords: ['ai', 'llm', 'rag', 'embedding', 'gpt', 'anthropic', 'openai', 'vector', 'semantic search', 'chatbot', 'ml'],
    requiredCapabilities: ['user', 'frontend', 'backend', 'authService', 'ai', 'embedding', 'vectorDb', 'documentDb', 'objectStorage', 'queue', 'worker', 'cache', 'monitoring', 'cicdPipeline', 'secrets', 'rateLimiter', 'backup'],
    recommendedComponents: ['ingestion', 'dlq', 'logging', 'alerting'],
    recommendedViews: ['systemContext', 'container', 'deployment', 'dataFlow', 'security', 'observability', 'scalingFailure'],
    commonFlows: ['Docs → Ingestion → Chunk → Embed → Vector store', 'Query → Embed → Retrieve top-k → LLM → Answer', 'Async ingestion via queue + worker'],
    securityControls: [...BASE_SECURITY, 'Prompt-injection aware input handling', 'PII scrubbing before embedding'],
    scalabilityControls: [...BASE_SCALE, 'Batch embedding jobs', 'Cache frequent retrievals and completions'],
    observabilityControls: [...BASE_OBS, 'Token usage + latency per model call'],
    commonAntiPatterns: ['Synchronous bulk ingestion in request path', 'No retrieval evaluation', 'Storing secrets in prompts'],
    cloudProviderMappings: { compute: 'computeContainer', db: 'documentDb' },
  },
  {
    id: 'resume-matching-platform',
    name: 'Resume analysis / job matching platform',
    category: 'ai',
    useCases: ['resume scoring', 'job matching', 'ATS tooling', 'career platform'],
    keywords: ['resume', 'job matching', 'ats', 'career', 'recruiter', 'candidate', 'job board', 'skill gap'],
    requiredCapabilities: ['user', 'frontend', 'backend', 'authService', 'rbac', 'decisionEngine', 'documentDb', 'objectStorage', 'queue', 'worker', 'cache', 'search', 'monitoring', 'auditLog', 'cicdPipeline', 'secrets', 'rateLimiter', 'backup'],
    recommendedComponents: ['ai', 'notifications', 'logging', 'alerting'],
    recommendedViews: ['systemContext', 'container', 'deployment', 'dataFlow', 'security', 'observability', 'scalingFailure'],
    commonFlows: ['Upload resume → Object storage → Parse worker → Score engine → Profile', 'Job feed → Match engine → Ranked results', 'Recruiter actions → Audit log'],
    securityControls: [...BASE_SECURITY, 'PII encryption at rest', 'Audit logs for recruiter/admin actions', 'Strict per-user data isolation'],
    scalabilityControls: BASE_SCALE,
    observabilityControls: BASE_OBS,
    commonAntiPatterns: ['AI-fabricated scores (scores must be deterministic)', 'Storing resumes as DB blobs', 'No audit trail'],
    cloudProviderMappings: { compute: 'computeContainer', db: 'documentDb' },
  },
  {
    id: 'devops-cicd-platform',
    name: 'DevOps CI/CD platform',
    category: 'devops',
    useCases: ['build pipeline product', 'deployment automation', 'internal developer platform'],
    keywords: ['ci/cd', 'cicd', 'pipeline', 'devops', 'terraform', 'jenkins', 'github actions', 'deployment', 'helm'],
    requiredCapabilities: ['user', 'sourceRepo', 'cicdPipeline', 'registry', 'backend', 'authService', 'queue', 'worker', 'relationalDb', 'objectStorage', 'secrets', 'monitoring', 'logging', 'alerting', 'rateLimiter', 'backup', 'iac'],
    recommendedComponents: ['cache', 'eventBus', 'frontend'],
    recommendedViews: ['systemContext', 'container', 'deployment', 'cicd', 'security', 'observability', 'scalingFailure'],
    commonFlows: ['Push → Webhook → Queue → Build workers → Registry', 'Deploy → Health checks → Rollback on failure'],
    securityControls: [...BASE_SECURITY, 'Signed artifacts', 'Least-privilege deploy credentials', 'Secrets injected at runtime only'],
    scalabilityControls: ['Autoscaled build worker pool', 'Build cache layers', 'Queue-based backpressure'],
    observabilityControls: [...BASE_OBS, 'Per-pipeline duration + failure-rate metrics'],
    commonAntiPatterns: ['Long-lived static build agents with stale state', 'Secrets baked into images'],
    cloudProviderMappings: { compute: 'computeContainer', db: 'relationalDb' },
  },
  {
    id: 'marketplace-platform',
    name: 'Marketplace platform',
    category: 'web',
    useCases: ['two-sided marketplace', 'listings + buyers + sellers', 'booking platform'],
    keywords: ['marketplace', 'listing', 'buyer', 'seller', 'booking', 'ecommerce', 'order', 'cart', 'payment'],
    requiredCapabilities: ['user', 'cdn', 'frontend', 'backend', 'authService', 'rbac', 'relationalDb', 'cache', 'search', 'queue', 'worker', 'payments', 'notifications', 'objectStorage', 'monitoring', 'auditLog', 'cicdPipeline', 'secrets', 'rateLimiter', 'backup'],
    recommendedComponents: ['waf', 'eventBus', 'logging', 'alerting'],
    recommendedViews: ['systemContext', 'container', 'deployment', 'dataFlow', 'security', 'observability', 'scalingFailure'],
    commonFlows: ['Search → Cache/Search index → Listings', 'Order → Payment provider → Webhook → Order state machine', 'Notifications via queue'],
    securityControls: [...BASE_SECURITY, 'Payment webhooks verified by signature', 'Idempotent order processing', 'Fraud/rate controls'],
    scalabilityControls: [...BASE_SCALE, 'Search index for catalog queries'],
    observabilityControls: BASE_OBS,
    commonAntiPatterns: ['Trusting client-side prices', 'Non-idempotent payment handlers'],
    cloudProviderMappings: { compute: 'computeContainer', db: 'relationalDb' },
  },
  {
    id: 'exam-proctoring-platform',
    name: 'Online exam / proctoring platform',
    category: 'web',
    useCases: ['online exams', 'mock tests', 'proctoring', 'assessments'],
    keywords: ['exam', 'proctor', 'test', 'quiz', 'assessment', 'mock test', 'question bank', 'grading'],
    requiredCapabilities: ['user', 'adminUser', 'cdn', 'frontend', 'backend', 'authService', 'rbac', 'relationalDb', 'cache', 'queue', 'worker', 'objectStorage', 'monitoring', 'auditLog', 'cicdPipeline', 'secrets', 'rateLimiter', 'backup'],
    recommendedComponents: ['notifications', 'streamProcessor', 'logging', 'alerting'],
    recommendedViews: ['systemContext', 'container', 'deployment', 'dataFlow', 'security', 'observability', 'scalingFailure'],
    commonFlows: ['Exam start → Session lock → Timed submission', 'Proctor media → Object storage → Async review worker', 'Grading worker → Results'],
    securityControls: [...BASE_SECURITY, 'Server-side timers (never trust client clocks)', 'Audit log of every exam event', 'Question bank access controls'],
    scalabilityControls: ['Pre-warm capacity for exam start spikes', ...BASE_SCALE],
    observabilityControls: BASE_OBS,
    commonAntiPatterns: ['Client-side grading', 'No exam-start load planning'],
    cloudProviderMappings: { compute: 'computeContainer', db: 'relationalDb' },
  },
  {
    id: 'patent-intelligence-platform',
    name: 'Patent workflow / intelligence platform',
    category: 'ai',
    useCases: ['patent drafting workflow', 'prior-art analysis', 'invention disclosure management'],
    keywords: ['patent', 'prior art', 'invention', 'disclosure', 'claims', 'ip ', 'novelty'],
    requiredCapabilities: ['user', 'frontend', 'backend', 'authService', 'rbac', 'decisionEngine', 'documentDb', 'search', 'objectStorage', 'queue', 'worker', 'cache', 'monitoring', 'auditLog', 'cicdPipeline', 'secrets', 'rateLimiter', 'backup'],
    recommendedComponents: ['ai', 'vectorDb', 'logging', 'alerting'],
    recommendedViews: ['systemContext', 'container', 'dataFlow', 'security', 'observability', 'patentFigure'],
    commonFlows: ['Disclosure intake → Scoring engine → Prior-art search → Report', 'Document versions → Audit trail'],
    securityControls: [...BASE_SECURITY, 'Confidential document encryption', 'Full audit trail (IP-sensitive data)'],
    scalabilityControls: BASE_SCALE,
    observabilityControls: BASE_OBS,
    commonAntiPatterns: ['Claiming patentability automatically', 'No document versioning'],
    cloudProviderMappings: { compute: 'computeContainer', db: 'documentDb' },
  },
  {
    id: 'placement-analytics-platform',
    name: 'College placement analytics platform',
    category: 'data',
    useCases: ['placement tracking', 'college analytics', 'student readiness dashboards'],
    keywords: ['placement', 'college', 'campus', 'student analytics', 'tpo', 'cohort', 'readiness'],
    requiredCapabilities: ['user', 'adminUser', 'frontend', 'backend', 'authService', 'rbac', 'relationalDb', 'cache', 'queue', 'worker', 'dataWarehouse', 'monitoring', 'auditLog', 'cicdPipeline', 'secrets', 'rateLimiter', 'backup'],
    recommendedComponents: ['notifications', 'objectStorage', 'logging', 'alerting'],
    recommendedViews: ['systemContext', 'container', 'deployment', 'dataFlow', 'security', 'observability'],
    commonFlows: ['Student events → ETL worker → Warehouse → Dashboards', 'Role-scoped views: student / TPO / recruiter'],
    securityControls: [...BASE_SECURITY, 'Role-scoped data access (student vs admin vs recruiter)', 'Audit logs for admin exports'],
    scalabilityControls: ['Aggregate offline in workers; serve precomputed dashboards', ...BASE_SCALE],
    observabilityControls: BASE_OBS,
    commonAntiPatterns: ['Heavy analytics queries on the OLTP database'],
    cloudProviderMappings: { compute: 'computeContainer', db: 'relationalDb' },
  },
  {
    id: 'event-driven-pipeline',
    name: 'Event-driven data pipeline',
    category: 'data',
    useCases: ['streaming ETL', 'real-time analytics', 'CDC pipelines', 'event processing'],
    keywords: ['kafka', 'stream', 'streaming', 'etl', 'pipeline', 'spark', 'airflow', 'data engineering', 'cdc', 'real-time', 'realtime', 'iceberg', 'databricks', 'snowflake'],
    requiredCapabilities: ['externalSystem', 'ingestion', 'eventBus', 'streamProcessor', 'queue', 'worker', 'dataWarehouse', 'objectStorage', 'relationalDb', 'monitoring', 'alerting', 'cicdPipeline', 'secrets', 'dlq', 'backup'],
    recommendedComponents: ['scheduler', 'cache', 'logging', 'iac'],
    recommendedViews: ['systemContext', 'container', 'deployment', 'dataFlow', 'observability', 'scalingFailure'],
    commonFlows: ['Sources → Ingestion → Event bus → Stream processor → Lake/Warehouse', 'Bad records → DLQ → Replay', 'Batch backfill via scheduler'],
    securityControls: [...BASE_SECURITY, 'Schema registry + validation at ingestion', 'Encrypted topics / buckets'],
    scalabilityControls: ['Partitioned topics with consumer groups', 'Idempotent, replayable consumers', 'Tiered storage (hot/warm/cold)'],
    observabilityControls: [...BASE_OBS, 'Consumer lag + data freshness metrics', 'Data quality checks with alerting'],
    commonAntiPatterns: ['Non-idempotent consumers', 'No DLQ', 'Schema-less ingestion'],
    cloudProviderMappings: { compute: 'streamProcessor', db: 'dataWarehouse' },
  },
  {
    id: 'serverless-api-platform',
    name: 'Serverless API platform',
    category: 'web',
    useCases: ['low-ops API', 'spiky traffic API', 'event-triggered backend'],
    keywords: ['serverless', 'lambda', 'cloud functions', 'faas', 'api gateway', 'dynamo'],
    requiredCapabilities: ['user', 'apiGateway', 'serverlessFn', 'authService', 'documentDb', 'queue', 'objectStorage', 'monitoring', 'cicdPipeline', 'secrets', 'rateLimiter', 'backup'],
    recommendedComponents: ['cdn', 'eventBus', 'dlq', 'cache', 'logging', 'alerting', 'iac'],
    recommendedViews: ['systemContext', 'container', 'deployment', 'dataFlow', 'security', 'cicd', 'observability'],
    commonFlows: ['Client → API Gateway → Function → DB', 'Events → Function → Queue → Function'],
    securityControls: [...BASE_SECURITY, 'Per-function least-privilege IAM roles'],
    scalabilityControls: ['Automatic scale-to-zero / scale-out', 'Provisioned concurrency for hot paths', 'Queue buffering for spikes'],
    observabilityControls: [...BASE_OBS, 'Cold-start and per-invocation cost metrics'],
    commonAntiPatterns: ['Long-running work inside request functions', 'Chatty function-to-function sync calls'],
    cloudProviderMappings: { compute: 'serverlessFn', db: 'documentDb' },
  },
  {
    id: 'k8s-cloud-native',
    name: 'Kubernetes cloud-native platform',
    category: 'devops',
    useCases: ['container platform', 'cloud-native product', 'multi-service deployment'],
    keywords: ['kubernetes', 'k8s', 'helm', 'istio', 'gke', 'eks', 'aks', 'cloud native', 'container orchestration'],
    requiredCapabilities: ['user', 'loadBalancer', 'apiGateway', 'computeContainer', 'backend', 'frontend', 'authService', 'relationalDb', 'cache', 'queue', 'worker', 'objectStorage', 'monitoring', 'tracing', 'logging', 'cicdPipeline', 'registry', 'iac', 'secrets', 'rateLimiter', 'backup'],
    recommendedComponents: ['eventBus', 'dlq', 'alerting'],
    recommendedViews: ['systemContext', 'container', 'deployment', 'cicd', 'security', 'observability', 'scalingFailure'],
    commonFlows: ['Ingress → Services → Pods', 'GitOps: commit → pipeline → registry → rollout', 'HPA-driven scaling on metrics'],
    securityControls: [...BASE_SECURITY, 'Network policies between namespaces', 'Pod security standards + image scanning'],
    scalabilityControls: ['Horizontal Pod Autoscaler', 'Cluster autoscaler', 'PodDisruptionBudgets for safe rollouts'],
    observabilityControls: [...BASE_OBS, 'Cluster + pod-level metrics'],
    commonAntiPatterns: ['Running Kubernetes for a single small app', 'Latest-tag images', 'No resource limits'],
    cloudProviderMappings: { compute: 'computeContainer', db: 'relationalDb' },
  },
];

/* ---- 4. Diagram templates (per-view defaults + layout hints) ---- */
export const DIAGRAM_TEMPLATES = {
  systemContext: {
    title: 'System Context',
    layout: 'layered',
    description: 'Who uses the system and what it talks to (C4 level 1).',
    groups: [
      { id: 'g-actors', label: 'Actors', type: 'zone', order: 0 },
      { id: 'g-system', label: 'System', type: 'boundary', order: 1 },
      { id: 'g-external', label: 'External Systems', type: 'zone', order: 2 },
    ],
  },
  container: {
    title: 'Container / Component',
    layout: 'layered',
    description: 'Deployable units and how they communicate (C4 level 2).',
    groups: [
      { id: 'g-actors', label: 'Actors', type: 'zone', order: 0 },
      { id: 'g-edge', label: 'Edge Layer', type: 'layer', order: 1 },
      { id: 'g-app', label: 'Application Layer', type: 'layer', order: 2 },
      { id: 'g-async', label: 'Async / Event Layer', type: 'layer', order: 3 },
      { id: 'g-data', label: 'Data Layer', type: 'layer', order: 4 },
      { id: 'g-external', label: 'External Services', type: 'zone', order: 5 },
    ],
  },
  deployment: {
    title: 'Cloud Deployment',
    layout: 'nested',
    description: 'How containers map onto cloud infrastructure.',
    groups: [
      { id: 'g-internet', label: 'Internet', type: 'zone', order: 0 },
      { id: 'g-region', label: 'Cloud Region', type: 'region', order: 1 },
      { id: 'g-edge', label: 'Edge Services', type: 'zone', parentId: 'g-region', order: 0 },
      { id: 'g-vpc', label: 'VPC / Virtual Network', type: 'vpc', parentId: 'g-region', order: 1 },
      { id: 'g-public', label: 'Public Subnet', type: 'subnet', parentId: 'g-vpc', order: 0 },
      { id: 'g-private', label: 'Private Subnet (app)', type: 'subnet', parentId: 'g-vpc', order: 1 },
      { id: 'g-datasubnet', label: 'Private Subnet (data)', type: 'subnet', parentId: 'g-vpc', order: 2 },
      { id: 'g-managed', label: 'Managed Services', type: 'zone', parentId: 'g-region', order: 2 },
    ],
  },
  dataFlow: {
    title: 'Data Flow',
    layout: 'sequence',
    description: 'Numbered path of a core request through the system.',
    groups: [],
  },
  security: {
    title: 'Security',
    layout: 'layered',
    description: 'Trust boundaries and security controls in request order.',
    groups: [
      { id: 'g-untrusted', label: 'Untrusted Zone', type: 'zone', order: 0 },
      { id: 'g-edge-sec', label: 'Edge Security Boundary', type: 'boundary', order: 1 },
      { id: 'g-app-sec', label: 'Application Trust Zone', type: 'boundary', order: 2 },
      { id: 'g-data-sec', label: 'Data Trust Zone', type: 'boundary', order: 3 },
    ],
  },
  cicd: {
    title: 'CI/CD',
    layout: 'sequence',
    description: 'Path from commit to production with quality gates.',
    groups: [
      { id: 'g-dev', label: 'Development', type: 'zone', order: 0 },
      { id: 'g-pipeline', label: 'Pipeline', type: 'zone', order: 1 },
      { id: 'g-runtime', label: 'Runtime', type: 'zone', order: 2 },
    ],
  },
  observability: {
    title: 'Observability',
    layout: 'layered',
    description: 'Logs, metrics, traces and alerting wiring.',
    groups: [
      { id: 'g-sources', label: 'Telemetry Sources', type: 'zone', order: 0 },
      { id: 'g-collect', label: 'Collection & Storage', type: 'layer', order: 1 },
      { id: 'g-act', label: 'Insight & Action', type: 'layer', order: 2 },
    ],
  },
  scalingFailure: {
    title: 'Scaling & Failure',
    layout: 'layered',
    description: 'How the system scales out and survives failures.',
    groups: [
      { id: 'g-traffic', label: 'Traffic', type: 'zone', order: 0 },
      { id: 'g-scale', label: 'Scaling Plane', type: 'layer', order: 1 },
      { id: 'g-resilience', label: 'Resilience Plane', type: 'layer', order: 2 },
    ],
  },
  patentFigure: {
    title: 'Patent Figure',
    layout: 'layered',
    description: 'Figure-ready system/process diagram (modules + data transformation). Not a patentability claim.',
    groups: [
      { id: 'g-fig-actors', label: 'Users / Operators', type: 'zone', order: 0 },
      { id: 'g-fig-modules', label: 'System Modules', type: 'boundary', order: 1 },
      { id: 'g-fig-engine', label: 'Processing / Decision Engine', type: 'boundary', order: 2 },
      { id: 'g-fig-store', label: 'Storage & Indexing', type: 'boundary', order: 3 },
    ],
  },
};

export const VIEW_TYPES = Object.keys(DIAGRAM_TEMPLATES);

export default { KB_VERSION, CAPABILITY_CATALOG, CLOUD_SERVICES, ARCHITECTURE_PATTERNS, DIAGRAM_TEMPLATES, VIEW_TYPES };
