/* ============================================================
   TEMPLATE OS — BUILTIN PREMIUM DEFINITIONS
   ------------------------------------------------------------
   The first genuinely multi-geometry templates, expressed purely
   as DSL data and compiled by the layout compiler — no bespoke
   React components. The technical family demonstrates
   inheritance: one base geometry, role-specific overrides.
   All are INTERNAL_ORIGINAL and production-enabled; their ATS
   level is measured by certification, not asserted.
   ============================================================ */
import { extendTemplate, TEMPLATE_DSL_VERSION } from './dsl.js';

const LIC = { licenseStatus: 'INTERNAL_ORIGINAL', source: 'Career Autopilot design team', licenseName: '', licenseNotice: '', productionEnabled: true };

/* ---- family base: technical sidebar ---- */
export const TECHNICAL_SIDEBAR_BASE = {
  dslVersion: TEMPLATE_DSL_VERSION,
  id: 'technical-sidebar-base',
  name: 'Technical Sidebar Base',
  version: 1,
  status: 'APPROVED',
  category: 'technical',
  tags: ['base', 'sidebar', 'technical'],
  supportedRoles: [],
  careerStages: ['early', 'mid', 'senior'],
  layout: { type: 'sidebar-left', columns: [{ id: 'sidebar', width: 0.3 }, { id: 'main', width: 0.7 }] },
  sectionPlacement: {
    skills: { region: 'sidebar', fallback: 'main' },
    certifications: { region: 'sidebar', fallback: 'main' },
    education: { region: 'sidebar', fallback: 'main' },
    languages: { region: 'sidebar', fallback: 'main' },
    summary: 'main', experience: 'main', projects: 'main', achievements: { region: 'main', fallback: 'sidebar' },
    publications: 'main', patents: 'main', volunteer: 'main', customSections: 'main',
  },
  sectionOrder: ['summary', 'experience', 'projects', 'skills', 'certifications', 'education', 'achievements'],
  headerStyle: { primitive: 'technical' },
  skillStyle: { primitive: 'sidebar-groups' },
  experienceStyle: { primitive: 'technical' },
  projectStyle: { primitive: 'evidence' },
  sectionStyles: { divider: 'accent-rule' },
  typography: { preset: 'engineering-mix' },
  spacing: { preset: 'balanced' },
  colors: { preset: 'slate' },
  contentBudget: { summary: { preferredLines: 3, maxLines: 4 }, currentExperience: { preferredBullets: 4, maxBullets: 6 }, previousExperience: { preferredBullets: 2, maxBullets: 4 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 18, maxCount: 26 }, certifications: { preferredCount: 4, maxCount: 6 }, achievements: { preferredCount: 2, maxCount: 4 } },
  exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'simplified-single-column' },
  license: { ...LIC },
};

export const TEMPLATE_OS_BUILTINS = [
  extendTemplate(TECHNICAL_SIDEBAR_BASE, {
    id: 'technical-sidebar', name: 'Technical Sidebar', status: 'PUBLISHED',
    description: 'Premium technical rail with content-aware height, balanced contact grid, compact reference hierarchy, and a wide experience-first main column.',
    supportedRoles: ['software', 'backend', 'frontend', 'full stack', 'engineer'],
    layout: { type: 'sidebar-left', columns: [{ id: 'sidebar', width: 0.31 }, { id: 'main', width: 0.69 }] },
    headerStyle: { primitive: 'technical', contactGridColumns: 2 },
    visualStyle: { sidebarPanel: 'premium-content' },
    spacing: { preset: 'balanced', sectionGapPx: 12.5, itemGapPx: 6.5, bulletGapPx: 3.2 },
  }),
  extendTemplate(TECHNICAL_SIDEBAR_BASE, {
    id: 'cloud-infrastructure-pro', name: 'Cloud Infrastructure Pro', status: 'PUBLISHED',
    description: 'DevOps/cloud flagship with a narrow certification-first right rail, infrastructure stack labels, compact evidence projects, and a restrained teal engineering identity.',
    supportedRoles: ['devops', 'cloud', 'platform', 'sre', 'infrastructure'],
    layout: { type: 'sidebar-right', columns: [{ id: 'main', width: 0.72 }, { id: 'sidebar', width: 0.28 }] },
    sectionPlacement: {
      certifications: { region: 'sidebar', fallback: 'main' },
      skills: { region: 'sidebar', fallback: 'main' },
      education: { region: 'sidebar', fallback: 'main' },
      summary: 'main', experience: 'main', projects: 'main', achievements: { region: 'main', fallback: 'sidebar' },
    },
    headerStyle: { primitive: 'technical', contactGridColumns: 2, accentMark: 'none', primaryInsetPx: 0 },
    skillStyle: { primitive: 'sidebar-groups', groupGapScale: 0.94, itemSizeScale: 0.91, labelSizeScale: 0.94 },
    experienceStyle: { primitive: 'cloud-platform' },
    projectStyle: { primitive: 'evidence-compact' },
    sectionStyles: { divider: 'hairline' },
    typography: { preset: 'cloud-engineering' },
    spacing: { preset: 'balanced', sectionGapPx: 12.5, itemGapPx: 6.2, bulletGapPx: 3 },
    colors: { preset: 'teal' },
    visualStyle: { sidebarPanel: 'cloud-rail', headerRule: 'accent', certificationBlock: 'featured', projectMeta: 'accent', verifiedBadge: 'soft' },
    sectionOrder: ['summary', 'experience', 'projects', 'certifications', 'skills', 'education', 'achievements'],
    contentBudget: { summary: { preferredLines: 2, maxLines: 3 }, currentExperience: { preferredBullets: 5, maxBullets: 6 }, previousExperience: { preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 18, maxCount: 26 }, certifications: { preferredCount: 4, maxCount: 6 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 3, maxBullets: 4 }, achievements: { preferredCount: 2, maxCount: 3 } },
  }),
  extendTemplate(TECHNICAL_SIDEBAR_BASE, {
    id: 'data-platform-sidebar', name: 'Data Platform', status: 'PUBLISHED',
    description: 'Data engineering variant: dense categorized stack in the rail, projects promoted above certifications, indigo accent.',
    supportedRoles: ['data engineer', 'analytics engineer', 'data platform', 'etl'],
    colors: { preset: 'indigo' },
    experienceStyle: { primitive: 'impact-first' },
  }),
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'balanced-two-column', name: 'Balanced Two Column', version: 1, status: 'PUBLISHED',
    description: 'Premium 38/62 editorial split — compact reference column left, experience-led narrative right, with a restrained gutter rule and corporate identity header.',
    category: 'professional', tags: ['two-column', 'editorial', 'design-forward', 'premium'],
    supportedRoles: ['product manager', 'consultant', 'marketing', 'designer'], careerStages: ['early', 'mid', 'senior'],
    layout: { type: 'two-column', columns: [{ id: 'left', width: 0.38 }, { id: 'right', width: 0.62 }] },
    sectionPlacement: { skills: 'left', certifications: 'left', education: 'left', achievements: 'left', languages: 'left', summary: 'right', experience: 'right', projects: 'right', publications: 'right', patents: 'right', volunteer: 'right', customSections: 'right' },
    sectionOrder: ['summary', 'experience', 'projects', 'skills', 'education', 'certifications', 'achievements'],
    headerStyle: { primitive: 'corporate', splitPrimaryShare: 0.62 }, skillStyle: { primitive: 'compact-matrix' },
    experienceStyle: { primitive: 'classic' }, projectStyle: { primitive: 'classic' },
    sectionStyles: { divider: 'short-rule' }, visualStyle: { columnTreatment: 'editorial-split' },
    typography: { preset: 'classic-serif' },
    spacing: { preset: 'balanced', marginMm: 17, sectionGapPx: 15.5, itemGapPx: 7.5, bulletGapPx: 3.8 },
    colors: { preset: 'burgundy' },
    contentBudget: { summary: { preferredLines: 3, maxLines: 4 }, currentExperience: { preferredBullets: 4, maxBullets: 5 }, previousExperience: { preferredBullets: 2, maxBullets: 3 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 2, maxBullets: 3 }, skills: { preferredCount: 12, maxCount: 18 }, certifications: { preferredCount: 3, maxCount: 5 }, achievements: { preferredCount: 3, maxCount: 5 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'simplified-single-column' },
    license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'editorial-professional', name: 'Editorial Professional', version: 1, status: 'PUBLISHED',
    description: 'Premium single-column editorial resume: full-width identity header, narrower reading measure, lead-profile typography and section labels that flow into quiet hairlines.',
    category: 'professional', tags: ['editorial', 'single-column', 'premium', 'corporate'],
    supportedRoles: ['consultant', 'finance', 'business', 'analyst'], careerStages: ['mid', 'senior', 'executive'],
    layout: { type: 'single-column' }, sectionPlacement: {},
    sectionOrder: ['summary', 'experience', 'skills', 'projects', 'education', 'certifications', 'achievements'],
    headerStyle: { primitive: 'editorial' },
    skillStyle: { primitive: 'inline', labelCase: 'upper', labelTone: 'muted', itemSizeScale: 0.98 },
    experienceStyle: { primitive: 'editorial' }, projectStyle: { primitive: 'classic', itemGapScale: 1.08 },
    sectionStyles: { divider: 'editorial-line' },
    visualStyle: { singleColumnTreatment: 'editorial-flow', summaryTreatment: 'editorial-lead' },
    typography: { preset: 'editorial-premium' },
    spacing: { preset: 'spacious', marginMm: 18, sectionGapPx: 17, itemGapPx: 8.5, bulletGapPx: 4.2 },
    colors: { preset: 'ink' },
    contentBudget: { summary: { preferredLines: 3, maxLines: 4 }, currentExperience: { preferredBullets: 4, maxBullets: 6 }, previousExperience: { preferredBullets: 3, maxBullets: 4 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 14, maxCount: 20 }, certifications: { preferredCount: 3, maxCount: 5 }, achievements: { preferredCount: 3, maxCount: 5 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'native' },
    license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'executive-technology', name: 'Executive Technology', version: 1, status: 'PUBLISHED',
    description: 'Leadership-first technology resume with an inverse executive identity band, impact-led experience, selected achievements near the top and deliberately reduced emphasis on raw skill density.',
    category: 'executive', tags: ['executive', 'leadership', 'technology', 'impact-first', 'premium'],
    supportedRoles: ['engineering manager', 'director', 'head of engineering', 'vp engineering', 'chief technology officer', 'principal engineer', 'staff engineer'], careerStages: ['senior', 'executive'],
    layout: { type: 'single-column' }, sectionPlacement: {},
    sectionOrder: ['summary', 'achievements', 'experience', 'skills', 'projects', 'education', 'certifications'],
    headerStyle: { primitive: 'executive', align: 'left', titleCase: 'upper', titleLetterSpacingPx: 0.7, contactSeparator: '  ·  ' },
    skillStyle: { primitive: 'inline', labelCase: 'upper', labelTone: 'muted', itemSizeScale: 0.96, groupGapScale: 0.72 },
    experienceStyle: { primitive: 'executive-impact' }, projectStyle: { primitive: 'compact', itemGapScale: 0.9 },
    sectionStyles: { divider: 'editorial-line' },
    visualStyle: { singleColumnTreatment: 'executive-flow', summaryTreatment: 'executive-lead' },
    typography: { preset: 'executive-premium' },
    spacing: { preset: 'balanced', marginMm: 16, sectionGapPx: 14, itemGapPx: 7, bulletGapPx: 3.5 },
    colors: { preset: 'executive-navy' },
    contentBudget: { summary: { preferredLines: 4, maxLines: 5 }, currentExperience: { preferredBullets: 5, maxBullets: 7 }, previousExperience: { preferredBullets: 3, maxBullets: 5 }, skills: { preferredCount: 12, maxCount: 18 }, projects: { preferredCount: 1, maxCount: 2, preferredBullets: 2, maxBullets: 3 }, certifications: { preferredCount: 2, maxCount: 4 }, achievements: { preferredCount: 3, maxCount: 5 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'native' },
    license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'campus-portfolio', name: 'Campus Portfolio', version: 1, status: 'PUBLISHED',
    description: 'Premium student/fresher portfolio: education and selected projects lead a wide narrative column while a compact content-height rail carries grouped skills, certifications and achievements.',
    category: 'student', tags: ['student', 'sidebar', 'projects-first', 'education-first', 'premium'],
    supportedRoles: ['student', 'intern', 'graduate', 'fresher'], careerStages: ['student', 'early'],
    layout: { type: 'sidebar-right', columns: [{ id: 'main', width: 0.7 }, { id: 'sidebar', width: 0.3 }] },
    sectionPlacement: { skills: { region: 'sidebar', fallback: 'main' }, certifications: { region: 'sidebar', fallback: 'main' }, achievements: { region: 'sidebar', fallback: 'main' }, languages: { region: 'sidebar', fallback: 'main' }, summary: 'main', education: 'main', projects: 'main', experience: 'main', publications: 'main', patents: 'main', volunteer: 'main', customSections: 'main' },
    sectionOrder: ['summary', 'education', 'projects', 'experience', 'skills', 'certifications', 'achievements'],
    headerStyle: { primitive: 'student', titleCase: 'upper', titleLetterSpacingPx: 0.45, accentMarkWidthPx: 42 },
    skillStyle: { primitive: 'sidebar-groups', groupGapScale: 0.9, itemSizeScale: 0.92, labelSizeScale: 0.94 },
    experienceStyle: { primitive: 'compact', itemGapScale: 0.9 },
    projectStyle: { primitive: 'student-portfolio' },
    educationStyle: { primitive: 'campus-featured' },
    sectionStyles: { divider: 'short-rule' },
    visualStyle: { sidebarPanel: 'student-rail', headerRule: 'none', certificationBlock: 'accent', projectMeta: 'accent', verifiedBadge: 'soft', summaryTreatment: 'student-intro' },
    typography: { preset: 'student-premium' },
    spacing: { preset: 'balanced', marginMm: 14, sectionGapPx: 13, itemGapPx: 6.5, bulletGapPx: 3.1 },
    colors: { preset: 'campus-blue' },
    contentBudget: { summary: { preferredLines: 2, maxLines: 3 }, currentExperience: { preferredBullets: 3, maxBullets: 4 }, previousExperience: { preferredBullets: 2, maxBullets: 3 }, projects: { preferredCount: 3, maxCount: 4, preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 12, maxCount: 18 }, certifications: { preferredCount: 2, maxCount: 4 }, achievements: { preferredCount: 2, maxCount: 4 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'simplified-single-column' },
    license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'signature-engineering', name: 'Signature Engineering', version: 1, status: 'PUBLISHED',
    description: 'Career Autopilot flagship: evidence-rich technical narrative with corporate identity, compact stack matrix, strong quantified experience and source-backed project depth.',
    category: 'technical', tags: ['flagship', 'engineering', 'platform', 'premium', 'single-column'],
    supportedRoles: ['software engineer', 'devops engineer', 'platform engineer', 'cloud engineer', 'site reliability engineer'], careerStages: ['mid', 'senior'],
    layout: { type: 'single-column' }, sectionPlacement: {},
    sectionOrder: ['summary', 'skills', 'experience', 'projects', 'certifications', 'education', 'achievements', 'publications', 'patents', 'volunteer', 'languages', 'customSections'],
    headerStyle: { primitive: 'corporate', splitPrimaryShare: 0.64 },
    skillStyle: { primitive: 'compact-matrix', itemSizeScale: 0.96 },
    experienceStyle: { primitive: 'cloud-platform', itemGapScale: 1.08 },
    projectStyle: { primitive: 'evidence', itemGapScale: 1.05 },
    sectionStyles: { divider: 'editorial-line' },
    visualStyle: { singleColumnTreatment: 'signature-flow', headerRule: 'accent', projectMeta: 'accent', verifiedBadge: 'soft', certificationBlock: 'accent' },
    typography: { preset: 'signature-sans' },
    spacing: { preset: 'balanced', marginMm: 15.5, sectionGapPx: 14.2, itemGapPx: 7.1, bulletGapPx: 3.5 },
    colors: { preset: 'graphite-blue' },
    contentBudget: { summary: { preferredLines: 3, maxLines: 4 }, currentExperience: { preferredBullets: 5, maxBullets: 6 }, previousExperience: { preferredBullets: 3, maxBullets: 4 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 16, maxCount: 22 }, certifications: { preferredCount: 3, maxCount: 5 }, achievements: { preferredCount: 2, maxCount: 4 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'native' }, license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'modern-corporate', name: 'Modern Corporate', version: 1, status: 'PUBLISHED',
    description: 'Clean corporate single-column family with split identity, restrained rules and impact-led experience for business, consulting and product-facing professionals.',
    category: 'professional', tags: ['corporate', 'consulting', 'business', 'premium'],
    supportedRoles: ['consultant', 'business analyst', 'finance analyst', 'product manager', 'program manager'], careerStages: ['early', 'mid', 'senior'],
    layout: { type: 'single-column' }, sectionPlacement: {},
    sectionOrder: ['summary', 'experience', 'achievements', 'skills', 'projects', 'education', 'certifications', 'publications', 'patents', 'volunteer', 'languages', 'customSections'],
    headerStyle: { primitive: 'corporate', splitPrimaryShare: 0.62 }, skillStyle: { primitive: 'inline', labelCase: 'upper', labelTone: 'muted' },
    experienceStyle: { primitive: 'impact-first' }, projectStyle: { primitive: 'classic' }, sectionStyles: { divider: 'hairline' },
    visualStyle: { singleColumnTreatment: 'corporate-flow', headerRule: 'hairline' }, typography: { preset: 'corporate-modern' },
    spacing: { preset: 'balanced', marginMm: 16.5, sectionGapPx: 15, itemGapPx: 7.5, bulletGapPx: 3.6 }, colors: { preset: 'product-blue' },
    contentBudget: { summary: { preferredLines: 3, maxLines: 4 }, currentExperience: { preferredBullets: 4, maxBullets: 6 }, previousExperience: { preferredBullets: 3, maxBullets: 4 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 2, maxBullets: 3 }, skills: { preferredCount: 14, maxCount: 20 }, certifications: { preferredCount: 3, maxCount: 5 }, achievements: { preferredCount: 3, maxCount: 5 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'native' }, license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'security-engineering', name: 'Security Engineering', version: 1, status: 'PUBLISHED',
    description: 'Precision security family with certification-first left rail, compact control/tool groups and incident/remediation-focused technical experience.',
    category: 'technical', tags: ['security', 'cybersecurity', 'devsecops', 'premium'],
    supportedRoles: ['security engineer', 'cloud security engineer', 'devsecops engineer', 'cybersecurity engineer'], careerStages: ['early', 'mid', 'senior'],
    layout: { type: 'sidebar-left', columns: [{ id: 'sidebar', width: 0.29 }, { id: 'main', width: 0.71 }] },
    sectionPlacement: { certifications: { region: 'sidebar', fallback: 'main' }, skills: { region: 'sidebar', fallback: 'main' }, education: { region: 'sidebar', fallback: 'main' }, languages: { region: 'sidebar', fallback: 'main' }, summary: 'main', experience: 'main', projects: 'main', achievements: 'main', publications: 'main', patents: 'main', volunteer: 'main', customSections: 'main' },
    sectionOrder: ['summary', 'experience', 'projects', 'certifications', 'skills', 'education', 'achievements', 'publications', 'patents', 'volunteer', 'languages', 'customSections'],
    headerStyle: { primitive: 'technical', contactGridColumns: 2 }, skillStyle: { primitive: 'sidebar-groups' }, experienceStyle: { primitive: 'technical' }, projectStyle: { primitive: 'evidence-compact' },
    sectionStyles: { divider: 'hairline' }, visualStyle: { sidebarPanel: 'premium-content', certificationBlock: 'featured', projectMeta: 'accent', verifiedBadge: 'outline' },
    typography: { preset: 'precision-sans' }, spacing: { preset: 'balanced', marginMm: 14.5, sectionGapPx: 12.5, itemGapPx: 6.3, bulletGapPx: 3 }, colors: { preset: 'security-steel' },
    contentBudget: { summary: { preferredLines: 2, maxLines: 3 }, currentExperience: { preferredBullets: 5, maxBullets: 6 }, previousExperience: { preferredBullets: 3, maxBullets: 4 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 18, maxCount: 26 }, certifications: { preferredCount: 4, maxCount: 6 }, achievements: { preferredCount: 2, maxCount: 4 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'simplified-single-column' }, license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'analytics-insight', name: 'Analytics Insight', version: 1, status: 'PUBLISHED',
    description: 'Data and analytics family with a narrow right reference rail, compact skill matrix and evidence-led analytical projects.',
    category: 'technical', tags: ['data', 'analytics', 'insights', 'premium'],
    supportedRoles: ['data analyst', 'analytics engineer', 'data scientist', 'business intelligence analyst'], careerStages: ['early', 'mid', 'senior'],
    layout: { type: 'sidebar-right', columns: [{ id: 'main', width: 0.7 }, { id: 'sidebar', width: 0.3 }] },
    sectionPlacement: { skills: { region: 'sidebar', fallback: 'main' }, certifications: { region: 'sidebar', fallback: 'main' }, education: { region: 'sidebar', fallback: 'main' }, languages: { region: 'sidebar', fallback: 'main' }, summary: 'main', experience: 'main', projects: 'main', achievements: 'main', publications: 'main', patents: 'main', volunteer: 'main', customSections: 'main' },
    sectionOrder: ['summary', 'experience', 'projects', 'skills', 'education', 'certifications', 'achievements', 'publications', 'patents', 'volunteer', 'languages', 'customSections'],
    headerStyle: { primitive: 'minimal' }, skillStyle: { primitive: 'compact-matrix' }, experienceStyle: { primitive: 'impact-first' }, projectStyle: { primitive: 'evidence' },
    sectionStyles: { divider: 'short-rule' }, visualStyle: { sidebarPanel: 'premium-content', projectMeta: 'accent', verifiedBadge: 'soft' }, typography: { preset: 'precision-sans' },
    spacing: { preset: 'balanced', marginMm: 15, sectionGapPx: 13.2, itemGapPx: 6.6, bulletGapPx: 3.2 }, colors: { preset: 'indigo' },
    contentBudget: { summary: { preferredLines: 3, maxLines: 4 }, currentExperience: { preferredBullets: 4, maxBullets: 6 }, previousExperience: { preferredBullets: 2, maxBullets: 4 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 18, maxCount: 26 }, certifications: { preferredCount: 3, maxCount: 5 }, achievements: { preferredCount: 2, maxCount: 4 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'simplified-single-column' }, license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'product-strategy', name: 'Product Strategy', version: 1, status: 'PUBLISHED',
    description: 'Product and strategy family with a compact evidence/reference column and a wider narrative column for launches, decisions and measurable outcomes.',
    category: 'professional', tags: ['product', 'strategy', 'leadership', 'two-column', 'premium'],
    supportedRoles: ['product manager', 'senior product manager', 'strategy consultant', 'program manager'], careerStages: ['mid', 'senior', 'executive'],
    layout: { type: 'two-column', columns: [{ id: 'left', width: 0.36 }, { id: 'right', width: 0.64 }] },
    sectionPlacement: { skills: 'left', education: 'left', certifications: 'left', languages: 'left', summary: 'right', experience: 'right', projects: 'right', achievements: 'right', publications: 'right', patents: 'right', volunteer: 'right', customSections: 'right' },
    sectionOrder: ['summary', 'achievements', 'experience', 'projects', 'skills', 'education', 'certifications', 'publications', 'patents', 'volunteer', 'languages', 'customSections'],
    headerStyle: { primitive: 'corporate', splitPrimaryShare: 0.64 }, skillStyle: { primitive: 'inline', labelCase: 'upper' }, experienceStyle: { primitive: 'impact-first' }, projectStyle: { primitive: 'classic' },
    sectionStyles: { divider: 'short-rule' }, visualStyle: { columnTreatment: 'editorial-split' }, typography: { preset: 'corporate-modern' },
    spacing: { preset: 'balanced', marginMm: 16.5, sectionGapPx: 14.5, itemGapPx: 7.3, bulletGapPx: 3.6 }, colors: { preset: 'product-blue' },
    contentBudget: { summary: { preferredLines: 3, maxLines: 4 }, currentExperience: { preferredBullets: 5, maxBullets: 6 }, previousExperience: { preferredBullets: 3, maxBullets: 4 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 2, maxBullets: 3 }, skills: { preferredCount: 12, maxCount: 18 }, certifications: { preferredCount: 3, maxCount: 5 }, achievements: { preferredCount: 4, maxCount: 6 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'simplified-single-column' }, license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'research-innovation', name: 'Research & Innovation', version: 1, status: 'PUBLISHED',
    description: 'Research-oriented editorial family that gives publications, patents and evidence projects first-class space without sacrificing ATS-safe linear structure.',
    category: 'professional', tags: ['research', 'innovation', 'publications', 'patents', 'premium'],
    supportedRoles: ['research engineer', 'research scientist', 'principal engineer', 'innovation lead'], careerStages: ['mid', 'senior', 'executive'],
    layout: { type: 'single-column' }, sectionPlacement: {},
    sectionOrder: ['summary', 'experience', 'publications', 'patents', 'projects', 'skills', 'education', 'certifications', 'achievements', 'volunteer', 'languages', 'customSections'],
    headerStyle: { primitive: 'editorial' }, skillStyle: { primitive: 'categorized', labelTone: 'muted' }, experienceStyle: { primitive: 'classic' }, projectStyle: { primitive: 'evidence' },
    sectionStyles: { divider: 'editorial-line' }, visualStyle: { singleColumnTreatment: 'research-flow', summaryTreatment: 'editorial-lead', projectMeta: 'accent', verifiedBadge: 'soft' },
    typography: { preset: 'research-serif' }, spacing: { preset: 'spacious', marginMm: 18, sectionGapPx: 16.5, itemGapPx: 8.2, bulletGapPx: 4 }, colors: { preset: 'research-maroon' },
    contentBudget: { summary: { preferredLines: 3, maxLines: 5 }, currentExperience: { preferredBullets: 4, maxBullets: 6 }, previousExperience: { preferredBullets: 3, maxBullets: 4 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 14, maxCount: 20 }, certifications: { preferredCount: 2, maxCount: 4 }, achievements: { preferredCount: 3, maxCount: 5 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'native' }, license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'minimal-ats-premium', name: 'Minimal ATS Premium', version: 1, status: 'PUBLISHED',
    description: 'Strict single-column ATS-first family with premium typography, restrained hairlines and zero decorative layout dependence.',
    category: 'professional', tags: ['ats', 'minimal', 'single-column', 'premium'],
    supportedRoles: ['software engineer', 'analyst', 'consultant', 'operations', 'general professional'], careerStages: ['student', 'early', 'mid', 'senior', 'executive'],
    layout: { type: 'single-column' }, sectionPlacement: {},
    sectionOrder: ['summary', 'skills', 'experience', 'projects', 'education', 'certifications', 'achievements', 'publications', 'patents', 'volunteer', 'languages', 'customSections'],
    headerStyle: { primitive: 'minimal' }, skillStyle: { primitive: 'plain' }, experienceStyle: { primitive: 'classic' }, projectStyle: { primitive: 'compact' },
    sectionStyles: { divider: 'hairline' }, visualStyle: {}, typography: { preset: 'strict-calibri' }, spacing: { preset: 'balanced', marginMm: 16, sectionGapPx: 13.5, itemGapPx: 6.7, bulletGapPx: 3.2 }, colors: { preset: 'monochrome' },
    contentBudget: { summary: { preferredLines: 3, maxLines: 4 }, currentExperience: { preferredBullets: 5, maxBullets: 7 }, previousExperience: { preferredBullets: 3, maxBullets: 5 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 2, maxBullets: 3 }, skills: { preferredCount: 18, maxCount: 28 }, certifications: { preferredCount: 4, maxCount: 6 }, achievements: { preferredCount: 3, maxCount: 5 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'native' }, license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'precision-engineering-classic', name: 'Precision Engineering Classic', version: 1, status: 'PUBLISHED',
    description: 'Dense premium engineering one-pager inspired by traditional recruiter-ready technical resumes: centered identity, grouped skill rows, compact role hierarchy and project depth without decorative layout risk.',
    category: 'technical', tags: ['precision', 'engineering', 'ats', 'single-column', 'premium'],
    supportedRoles: ['devops engineer', 'cloud engineer', 'platform engineer', 'software engineer', 'site reliability engineer'], careerStages: ['early', 'mid', 'senior'],
    layout: { type: 'single-column' }, sectionPlacement: {},
    sectionOrder: ['summary', 'skills', 'experience', 'projects', 'education', 'certifications', 'achievements', 'publications', 'patents', 'volunteer', 'languages', 'customSections'],
    headerStyle: { primitive: 'centered', contactSeparator: ' · ' }, skillStyle: { primitive: 'inline', labelCase: 'none', labelTone: 'text', itemSizeScale: 0.95 },
    experienceStyle: { primitive: 'classic', itemGapScale: 0.92 }, projectStyle: { primitive: 'classic', itemGapScale: 0.92 },
    sectionStyles: { divider: 'hairline' }, visualStyle: { singleColumnTreatment: 'signature-flow' }, typography: { preset: 'centered-ats-sans' },
    spacing: { preset: 'compact', marginMm: 13.5, sectionGapPx: 10.8, itemGapPx: 5.4, bulletGapPx: 2.6 }, colors: { preset: 'graphite-blue' },
    contentBudget: { summary: { preferredLines: 3, maxLines: 4 }, currentExperience: { preferredBullets: 6, maxBullets: 7 }, previousExperience: { preferredBullets: 2, maxBullets: 3 }, projects: { preferredCount: 2, maxCount: 2, preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 20, maxCount: 28 }, certifications: { preferredCount: 4, maxCount: 6 }, achievements: { preferredCount: 2, maxCount: 4 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'native' }, license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'heritage-detailed', name: 'Heritage Detailed', version: 1, status: 'PUBLISHED',
    description: 'Premium multi-page serif family with generous reading rhythm, rust rules and full-context experience/project depth for senior candidates who should not be compressed into a one-page layout.',
    category: 'professional', tags: ['heritage', 'detailed', 'serif', 'multi-page', 'premium'],
    supportedRoles: ['senior engineer', 'architect', 'consultant', 'program manager', 'principal engineer'], careerStages: ['mid', 'senior', 'executive'],
    layout: { type: 'single-column' }, sectionPlacement: {},
    sectionOrder: ['summary', 'skills', 'experience', 'projects', 'education', 'certifications', 'achievements', 'publications', 'patents', 'volunteer', 'languages', 'customSections'],
    headerStyle: { primitive: 'editorial', align: 'left' }, skillStyle: { primitive: 'inline', labelTone: 'text' }, experienceStyle: { primitive: 'classic', itemGapScale: 1.12 }, projectStyle: { primitive: 'classic', itemGapScale: 1.08 },
    sectionStyles: { divider: 'accent-rule' }, visualStyle: { singleColumnTreatment: 'editorial-flow', summaryTreatment: 'editorial-lead' }, typography: { preset: 'heritage-detailed-serif' },
    spacing: { preset: 'spacious', marginMm: 16.5, sectionGapPx: 16.5, itemGapPx: 8.2, bulletGapPx: 4.1 }, colors: { preset: 'reference-rust' },
    contentBudget: { summary: { preferredLines: 4, maxLines: 5 }, currentExperience: { preferredBullets: 7, maxBullets: 9 }, previousExperience: { preferredBullets: 4, maxBullets: 5 }, projects: { preferredCount: 3, maxCount: 4, preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 20, maxCount: 30 }, certifications: { preferredCount: 5, maxCount: 8 }, achievements: { preferredCount: 4, maxCount: 6 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'native' }, license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'graduate-violet', name: 'Graduate Violet', version: 1, status: 'PUBLISHED',
    description: 'Project-first fresher family with centered identity, education prominence, ATS-readable violet skill chips and enough project depth to make limited experience feel substantive without inventing sections.',
    category: 'student', tags: ['graduate', 'student', 'project-first', 'violet', 'premium'],
    supportedRoles: ['student', 'intern', 'graduate', 'fresher', 'junior engineer'], careerStages: ['student', 'early'],
    layout: { type: 'single-column' }, sectionPlacement: {},
    sectionOrder: ['summary', 'education', 'projects', 'skills', 'experience', 'certifications', 'achievements', 'publications', 'patents', 'volunteer', 'languages', 'customSections'],
    headerStyle: { primitive: 'student', accentMarkWidthPx: 0 }, skillStyle: { primitive: 'soft-chips', itemSizeScale: 0.88 }, experienceStyle: { primitive: 'compact' }, projectStyle: { primitive: 'student-portfolio' }, educationStyle: { primitive: 'campus-featured' },
    sectionStyles: { divider: 'accent-rule' }, visualStyle: { summaryTreatment: 'student-intro', projectMeta: 'accent' }, typography: { preset: 'modern-chip-sans' },
    spacing: { preset: 'balanced', marginMm: 14.5, sectionGapPx: 12.8, itemGapPx: 6.2, bulletGapPx: 3 }, colors: { preset: 'reference-violet' },
    contentBudget: { summary: { preferredLines: 2, maxLines: 3 }, currentExperience: { preferredBullets: 3, maxBullets: 4 }, previousExperience: { preferredBullets: 2, maxBullets: 3 }, projects: { preferredCount: 3, maxCount: 4, preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 18, maxCount: 28 }, certifications: { preferredCount: 3, maxCount: 5 }, achievements: { preferredCount: 3, maxCount: 5 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'native' }, license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'cloud-devops-modern', name: 'Cloud DevOps Modern', version: 1, status: 'PUBLISHED',
    description: 'Modern cloud/DevOps single-column family with a visible tooling cloud, strong blue rules, dense technical experience and source-backed infrastructure projects.',
    category: 'technical', tags: ['cloud', 'devops', 'chips', 'single-column', 'premium'],
    supportedRoles: ['devops engineer', 'cloud engineer', 'platform engineer', 'site reliability engineer', 'infrastructure engineer'], careerStages: ['early', 'mid', 'senior'],
    layout: { type: 'single-column' }, sectionPlacement: {},
    sectionOrder: ['summary', 'skills', 'experience', 'projects', 'education', 'certifications', 'achievements', 'publications', 'patents', 'volunteer', 'languages', 'customSections'],
    headerStyle: { primitive: 'minimal' }, skillStyle: { primitive: 'soft-chips', itemSizeScale: 0.9 }, experienceStyle: { primitive: 'cloud-platform' }, projectStyle: { primitive: 'evidence-compact' },
    sectionStyles: { divider: 'accent-rule' }, visualStyle: { headerRule: 'none', projectMeta: 'accent', verifiedBadge: 'soft' }, typography: { preset: 'modern-chip-sans' },
    spacing: { preset: 'compact', marginMm: 13.8, sectionGapPx: 11.5, itemGapPx: 5.8, bulletGapPx: 2.8 }, colors: { preset: 'reference-sky' },
    contentBudget: { summary: { preferredLines: 3, maxLines: 4 }, currentExperience: { preferredBullets: 6, maxBullets: 7 }, previousExperience: { preferredBullets: 2, maxBullets: 4 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 22, maxCount: 32 }, certifications: { preferredCount: 4, maxCount: 6 }, achievements: { preferredCount: 2, maxCount: 4 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'native' }, license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'midnight-technical-rail', name: 'Midnight Technical Rail', version: 1, status: 'PUBLISHED',
    description: 'High-contrast technical family with a full-height midnight reference rail for skills, education and certifications, paired with a bright experience-first narrative column.',
    category: 'technical', tags: ['midnight', 'sidebar', 'technical', 'high-contrast', 'premium'],
    supportedRoles: ['software engineer', 'devops engineer', 'cloud engineer', 'platform engineer', 'security engineer'], careerStages: ['early', 'mid', 'senior'],
    layout: { type: 'sidebar-left', columns: [{ id: 'sidebar', width: 0.32 }, { id: 'main', width: 0.68 }] },
    sectionPlacement: { skills: { region: 'sidebar', fallback: 'main' }, education: { region: 'sidebar', fallback: 'main' }, certifications: { region: 'sidebar', fallback: 'main' }, languages: { region: 'sidebar', fallback: 'main' }, summary: 'main', experience: 'main', projects: 'main', achievements: 'main', publications: 'main', patents: 'main', volunteer: 'main', customSections: 'main' },
    sectionOrder: ['summary', 'experience', 'projects', 'skills', 'education', 'certifications', 'achievements', 'publications', 'patents', 'volunteer', 'languages', 'customSections'],
    headerStyle: { primitive: 'compact' }, skillStyle: { primitive: 'soft-chips', itemSizeScale: 0.84, groupGapScale: 0.7 }, experienceStyle: { primitive: 'classic' }, projectStyle: { primitive: 'classic' },
    sectionStyles: { divider: 'accent-rule' }, visualStyle: { sidebarPanel: 'midnight-solid', projectMeta: 'accent' }, typography: { preset: 'midnight-rail-sans' },
    spacing: { preset: 'compact', marginMm: 12.5, sectionGapPx: 10.8, itemGapPx: 5.4, bulletGapPx: 2.7 }, colors: { preset: 'reference-midnight' },
    contentBudget: { summary: { preferredLines: 3, maxLines: 4 }, currentExperience: { preferredBullets: 6, maxBullets: 7 }, previousExperience: { preferredBullets: 2, maxBullets: 4 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 22, maxCount: 32 }, certifications: { preferredCount: 4, maxCount: 6 }, achievements: { preferredCount: 2, maxCount: 4 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'simplified-single-column' }, license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'minimal-serif-ats', name: 'Minimal Serif ATS', version: 1, status: 'PUBLISHED',
    description: 'Traditional black-on-white serif ATS family with centered identity, thin rules and zero dependence on visual containers, icons or sidebars.',
    category: 'professional', tags: ['ats', 'serif', 'minimal', 'traditional', 'premium'],
    supportedRoles: ['general professional', 'finance analyst', 'consultant', 'software engineer', 'operations'], careerStages: ['student', 'early', 'mid', 'senior', 'executive'],
    layout: { type: 'single-column' }, sectionPlacement: {},
    sectionOrder: ['summary', 'skills', 'experience', 'projects', 'education', 'certifications', 'achievements', 'publications', 'patents', 'volunteer', 'languages', 'customSections'],
    headerStyle: { primitive: 'centered' }, skillStyle: { primitive: 'plain' }, experienceStyle: { primitive: 'classic' }, projectStyle: { primitive: 'classic' },
    sectionStyles: { divider: 'hairline' }, visualStyle: {}, typography: { preset: 'precision-classic-serif' }, spacing: { preset: 'balanced', marginMm: 15, sectionGapPx: 12.3, itemGapPx: 6.2, bulletGapPx: 3 }, colors: { preset: 'monochrome' },
    contentBudget: { summary: { preferredLines: 3, maxLines: 4 }, currentExperience: { preferredBullets: 6, maxBullets: 8 }, previousExperience: { preferredBullets: 3, maxBullets: 4 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 22, maxCount: 32 }, certifications: { preferredCount: 5, maxCount: 7 }, achievements: { preferredCount: 3, maxCount: 5 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'native' }, license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'dark-executive-classic', name: 'Dark Executive Classic', version: 1, status: 'PUBLISHED',
    description: 'Premium dark-band serif executive family with warm bronze section rules and detailed leadership/technical evidence beneath a restrained high-contrast identity header.',
    category: 'executive', tags: ['executive', 'dark-header', 'serif', 'leadership', 'premium'],
    supportedRoles: ['engineering manager', 'director', 'principal engineer', 'head of engineering', 'technology leader'], careerStages: ['senior', 'executive'],
    layout: { type: 'single-column' }, sectionPlacement: {},
    sectionOrder: ['summary', 'achievements', 'skills', 'experience', 'projects', 'education', 'certifications', 'publications', 'patents', 'volunteer', 'languages', 'customSections'],
    headerStyle: { primitive: 'dark-executive-classic', align: 'left' }, skillStyle: { primitive: 'inline', labelTone: 'text' }, experienceStyle: { primitive: 'executive-impact' }, projectStyle: { primitive: 'classic' },
    sectionStyles: { divider: 'accent-rule' }, visualStyle: { summaryTreatment: 'executive-lead' }, typography: { preset: 'heritage-detailed-serif' }, spacing: { preset: 'balanced', marginMm: 15.5, sectionGapPx: 13.8, itemGapPx: 7.1, bulletGapPx: 3.4 }, colors: { preset: 'reference-amber' },
    contentBudget: { summary: { preferredLines: 4, maxLines: 5 }, currentExperience: { preferredBullets: 6, maxBullets: 8 }, previousExperience: { preferredBullets: 3, maxBullets: 5 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 16, maxCount: 24 }, certifications: { preferredCount: 4, maxCount: 6 }, achievements: { preferredCount: 4, maxCount: 6 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'native' }, license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'centered-ats-engineering', name: 'Centered ATS Engineering', version: 1, status: 'PUBLISHED',
    description: 'Compact centered engineering ATS family with dark rules, conservative typography and dense role/project evidence for portal submissions.',
    category: 'technical', tags: ['ats', 'centered', 'engineering', 'compact', 'premium'],
    supportedRoles: ['software engineer', 'devops engineer', 'backend engineer', 'cloud engineer', 'site reliability engineer'], careerStages: ['student', 'early', 'mid', 'senior'],
    layout: { type: 'single-column' }, sectionPlacement: {},
    sectionOrder: ['summary', 'skills', 'experience', 'projects', 'education', 'certifications', 'achievements', 'publications', 'patents', 'volunteer', 'languages', 'customSections'],
    headerStyle: { primitive: 'centered' }, skillStyle: { primitive: 'inline', labelTone: 'text' }, experienceStyle: { primitive: 'classic', itemGapScale: 0.9 }, projectStyle: { primitive: 'classic', itemGapScale: 0.9 },
    sectionStyles: { divider: 'hairline' }, visualStyle: {}, typography: { preset: 'centered-ats-sans' }, spacing: { preset: 'compact', marginMm: 13.5, sectionGapPx: 10.7, itemGapPx: 5.3, bulletGapPx: 2.55 }, colors: { preset: 'slate' },
    contentBudget: { summary: { preferredLines: 3, maxLines: 4 }, currentExperience: { preferredBullets: 6, maxBullets: 7 }, previousExperience: { preferredBullets: 2, maxBullets: 4 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 20, maxCount: 30 }, certifications: { preferredCount: 4, maxCount: 6 }, achievements: { preferredCount: 2, maxCount: 4 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'native' }, license: { ...LIC },
  },
  {
    dslVersion: TEMPLATE_DSL_VERSION,
    id: 'violet-modern-professional', name: 'Violet Modern Professional', version: 1, status: 'PUBLISHED',
    description: 'Contemporary single-column professional family with a confident left identity, violet section rules and restrained skill chips while retaining a normal semantic text flow.',
    category: 'professional', tags: ['modern', 'violet', 'chips', 'single-column', 'premium'],
    supportedRoles: ['software engineer', 'analyst', 'consultant', 'product professional', 'startup roles'], careerStages: ['early', 'mid', 'senior'],
    layout: { type: 'single-column' }, sectionPlacement: {},
    sectionOrder: ['summary', 'skills', 'experience', 'projects', 'education', 'certifications', 'achievements', 'publications', 'patents', 'volunteer', 'languages', 'customSections'],
    headerStyle: { primitive: 'minimal' }, skillStyle: { primitive: 'soft-chips', itemSizeScale: 0.9 }, experienceStyle: { primitive: 'impact-first' }, projectStyle: { primitive: 'classic' },
    sectionStyles: { divider: 'accent-rule' }, visualStyle: { projectMeta: 'accent' }, typography: { preset: 'modern-chip-sans' }, spacing: { preset: 'balanced', marginMm: 14.5, sectionGapPx: 12.5, itemGapPx: 6.2, bulletGapPx: 3 }, colors: { preset: 'reference-violet' },
    contentBudget: { summary: { preferredLines: 3, maxLines: 4 }, currentExperience: { preferredBullets: 5, maxBullets: 7 }, previousExperience: { preferredBullets: 3, maxBullets: 4 }, projects: { preferredCount: 2, maxCount: 3, preferredBullets: 3, maxBullets: 4 }, skills: { preferredCount: 20, maxCount: 30 }, certifications: { preferredCount: 4, maxCount: 6 }, achievements: { preferredCount: 3, maxCount: 5 } },
    exports: { pdf: true, html: true, txt: true, docx: true, docxProfile: 'native' }, license: { ...LIC },
  },
];


/* ------------------------------------------------------------------
   CERTIFICATION SNAPSHOT — measured on REAL PDF text layers by
   certifyDefinitionDeep (see pdfValidation.js). Checked in so gallery
   cards can show levels without re-parsing PDFs during typing.
   test/templateOs.test.js re-measures and FAILS if any value here
   drifts from reality, so these numbers cannot quietly become a claim.
   ------------------------------------------------------------------ */
export const BUILTIN_CERTIFICATION = Object.freeze({
  'technical-sidebar': { certified: true, atsLevel: 'HIGH', atsLevelMultiPage: 'BALANCED', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'cloud-infrastructure-pro': { certified: true, atsLevel: 'HIGH', atsLevelMultiPage: 'BALANCED', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'data-platform-sidebar': { certified: true, atsLevel: 'HIGH', atsLevelMultiPage: 'BALANCED', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'balanced-two-column': { certified: true, atsLevel: 'HIGH', atsLevelMultiPage: 'BALANCED', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'editorial-professional': { certified: true, atsLevel: 'VERY_HIGH', atsLevelMultiPage: 'VERY_HIGH', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'executive-technology': { certified: true, atsLevel: 'VERY_HIGH', atsLevelMultiPage: 'VERY_HIGH', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'campus-portfolio': { certified: true, atsLevel: 'HIGH', atsLevelMultiPage: 'BALANCED', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'signature-engineering': { certified: true, atsLevel: 'VERY_HIGH', atsLevelMultiPage: 'VERY_HIGH', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'modern-corporate': { certified: true, atsLevel: 'VERY_HIGH', atsLevelMultiPage: 'VERY_HIGH', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'security-engineering': { certified: true, atsLevel: 'HIGH', atsLevelMultiPage: 'BALANCED', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'analytics-insight': { certified: true, atsLevel: 'HIGH', atsLevelMultiPage: 'BALANCED', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'product-strategy': { certified: true, atsLevel: 'HIGH', atsLevelMultiPage: 'BALANCED', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'research-innovation': { certified: true, atsLevel: 'VERY_HIGH', atsLevelMultiPage: 'VERY_HIGH', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'minimal-ats-premium': { certified: true, atsLevel: 'VERY_HIGH', atsLevelMultiPage: 'VERY_HIGH', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'precision-engineering-classic': { certified: true, atsLevel: 'VERY_HIGH', atsLevelMultiPage: 'VERY_HIGH', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'heritage-detailed': { certified: true, atsLevel: 'VERY_HIGH', atsLevelMultiPage: 'VERY_HIGH', minIntegrity: 100, minOrderScore: 100, maxPages: 3, evidence: 'real-pdf-text-layer' },
  'graduate-violet': { certified: true, atsLevel: 'VERY_HIGH', atsLevelMultiPage: 'VERY_HIGH', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'cloud-devops-modern': { certified: true, atsLevel: 'VERY_HIGH', atsLevelMultiPage: 'VERY_HIGH', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'midnight-technical-rail': { certified: true, atsLevel: 'HIGH', atsLevelMultiPage: 'BALANCED', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'minimal-serif-ats': { certified: true, atsLevel: 'VERY_HIGH', atsLevelMultiPage: 'VERY_HIGH', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'dark-executive-classic': { certified: true, atsLevel: 'VERY_HIGH', atsLevelMultiPage: 'VERY_HIGH', minIntegrity: 100, minOrderScore: 100, maxPages: 3, evidence: 'real-pdf-text-layer' },
  'centered-ats-engineering': { certified: true, atsLevel: 'VERY_HIGH', atsLevelMultiPage: 'VERY_HIGH', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
  'violet-modern-professional': { certified: true, atsLevel: 'VERY_HIGH', atsLevelMultiPage: 'VERY_HIGH', minIntegrity: 100, minOrderScore: 100, maxPages: 2, evidence: 'real-pdf-text-layer' },
});

export default { TEMPLATE_OS_BUILTINS, TECHNICAL_SIDEBAR_BASE, BUILTIN_CERTIFICATION };
