/* ============================================================
   Synthesis Intelligence — domain profiles (deterministic KB)
   ------------------------------------------------------------
   Reusable, dependency-free, domain-aware fallback generators.
   Each profile carries domain-specific target users, technical
   mechanisms, modules, architecture, data sources, DB models,
   skills, milestones and proof checklists so that fallback /
   low-confidence output is still concrete and buildable — and
   so two unrelated domains can never produce identical
   blueprint structures.
   ============================================================ */

const p = (profile) => profile; // identity, keeps each block readable

export const DOMAIN_PROFILES = {
  simulation: p({
    key: 'simulation',
    label: 'Simulation / Digital Twin',
    match: ['simulation', 'simulator', 'digital twin', 'twin', 'virtual training', 'scenario engine', 'physics', 'driving simulator', 'flight simulator', 'vehicle training', 'training simulator'],
    subdomains: ['vehicle/driver training', 'industrial digital twin', 'process simulation', 'emergency-drill simulation'],
    targetUsers: ['driving-school instructors', 'industrial plant operators', 'safety trainers', 'engineering students learning system dynamics'],
    mechanisms: [
      { name: 'discrete-event simulation engine', summary: 'A deterministic tick/step loop that advances entity state from configurable scenario parameters and records every state transition for replay.' },
      { name: 'physics-state propagation engine', summary: 'Numerically integrates motion/process state per frame (position, velocity, load) with bounded error and deterministic seeds for repeatable runs.' },
      { name: 'scenario scoring and replay engine', summary: 'Scores each run against rubric events (violations, reaction times, thresholds) and reconstructs the timeline from the event log.' },
    ],
    modules: ['Scenario definition module (parameterised environments, hazards, difficulty curves)', 'Simulation core (tick loop, entity state machine, deterministic seed control)', 'Telemetry recorder (per-tick event log for replay and scoring)', 'Performance scoring rubric (reaction time, violations, completion quality)', 'Replay and debrief viewer with timeline scrubbing', 'Instructor dashboard for cohort comparison'],
    architecture: ['Scenario config store → simulation core (server-side tick loop or in-browser worker)', 'Telemetry event stream → append-only run log', 'Scoring service consumes the run log (never the live loop) → deterministic score', 'Replay viewer renders from the persisted event log', 'Instructor/admin views aggregate scores across runs'],
    techStack: ['React + canvas/WebGL (Three.js) for the simulated view', 'Node.js (Express) for scenario/run APIs', 'Web Worker or server tick loop for the simulation core', 'MongoDB for scenarios, runs and telemetry', 'Seedable RNG utility for reproducible runs'],
    dataSources: ['Self-generated telemetry (the simulation is the data source)', 'OpenStreetMap road/route geometry (for driving/route scenarios)', 'Published human-factors norms (reaction-time baselines) for rubric calibration'],
    databaseModels: ['scenarios(id, name, params, difficulty, hazards[])', 'runs(id, scenarioId, userId, seed, startedAt, finishedAt, score)', 'telemetry_events(runId, tick, entity, state, eventType)', 'rubrics(id, scenarioId, criteria[], weights)'],
    skills: ['state machines and game loops', 'numerical integration basics', 'event sourcing / replay design', 'canvas/WebGL rendering', 'deterministic testing with seeds'],
    milestones: ['Define one concrete scenario schema and build the deterministic tick loop with seeded RNG', 'Render the live simulation view and record full telemetry per tick', 'Implement rubric scoring computed purely from the telemetry log', 'Build replay/debrief view with timeline scrubbing', 'Add instructor dashboard, polish, demo dataset and recorded walkthrough'],
    proofChecklist: ['Two identical seeds produce byte-identical telemetry (determinism proof)', 'A recorded replay of a full scenario run', 'Scoring unit tests against hand-computed rubric outcomes', 'Public repo + short demo video of a scored training session'],
    testingPlan: ['Unit tests: tick loop determinism with fixed seeds', 'Unit tests: rubric scoring from canned telemetry logs', 'Integration: scenario → run → score → replay round-trip', 'Load test: telemetry write throughput for a 10-minute run'],
    deploymentPlan: ['Run simulation core in a Web Worker for the MVP (no server cost)', 'Deploy API + scenario store to a managed Node host', 'Store telemetry compressed; cap per-run event volume', 'CI: lint + tests + a headless scripted simulation run'],
    expectedOutput: 'A repeatable, scored simulation run with full replay — instructors see objective performance evidence instead of subjective impressions.',
    prototypeType: 'interactive simulation with scored replay',
    risks: ['Physics fidelity can absorb unlimited time — fix an explicit fidelity budget for the MVP', 'Telemetry volume grows fast; sample or compress early', 'Scores are only as defensible as the rubric — document rubric assumptions'],
    sensitivity: ['If trainee performance data identifies individuals, treat it as personnel data: restrict instructor access and define retention.'],
    ip: { appropriate: 'conditional', caution: 'Simulation methods with a concrete technical effect (deterministic replay, novel state-propagation step) may merit review; generic “training app” framing will not.' },
  }),

  healthcare: p({
    key: 'healthcare',
    label: 'Healthcare / Monitoring',
    match: ['health', 'healthcare', 'patient', 'clinical', 'hospital', 'medical', 'vitals', 'monitoring platform', 'diagnosis', 'pharma', 'wellness', 'remote monitoring'],
    subdomains: ['remote patient monitoring', 'medication adherence', 'clinical workflow tooling', 'public-health surveillance'],
    targetUsers: ['ward nurses tracking multiple patients', 'caregivers of chronic patients at home', 'clinic administrators', 'community health workers'],
    mechanisms: [
      { name: 'vitals anomaly detection pipeline', summary: 'Streams periodic vitals readings through per-patient rolling baselines and rule + statistical thresholds, emitting graded alerts with the triggering evidence attached.' },
      { name: 'event-driven escalation engine', summary: 'Routes alerts through an acknowledgement/escalation state machine (notify → ack timeout → escalate) with a full audit trail.' },
      { name: 'adherence scoring engine', summary: 'Computes deterministic adherence scores from dose-event logs and surfaces explainable misses, not opaque percentages.' },
    ],
    modules: ['Reading ingestion module (manual entry + device/CSV import)', 'Per-patient baseline calculator (rolling window statistics)', 'Threshold + trend anomaly detector with graded severities', 'Alert escalation state machine with audit log', 'Clinician dashboard (patient list ranked by risk, drill-down trends)', 'Consent and access-control module (role-scoped patient access)'],
    architecture: ['Ingestion API normalises readings into one observation schema', 'Stream/batch evaluator compares each reading against baseline + rules', 'Alert service persists alert state transitions (open → acked → escalated → resolved)', 'Dashboard reads ranked risk views; never recomputes scores client-side', 'Every access to patient data passes a role + consent check and is audit-logged'],
    techStack: ['React dashboard with trend charts', 'Node.js (Express) APIs', 'MongoDB with per-field access rules for observations/alerts', 'A rules table (not hard-coded ifs) for thresholds', 'Optional: simple statistical library for rolling z-scores'],
    dataSources: ['Manually entered or CSV-imported vitals (MVP)', 'openFDA for drug/adverse-event reference data', 'Synthetic patient generators for demo/testing (never real PHI in demos)'],
    databaseModels: ['patients(id, demographics_minimal, consentStatus)', 'observations(id, patientId, type, value, unit, takenAt, source)', 'baselines(patientId, type, mean, sd, windowDays)', 'alerts(id, patientId, severity, trigger, state, stateHistory[])', 'access_log(userId, patientId, action, at)'],
    skills: ['time-series baseline statistics', 'state-machine design for escalation', 'role-based access control around sensitive data', 'audit logging', 'clinical-safety-aware UX (alarm fatigue)'],
    milestones: ['Define the observation schema and build ingestion (manual + CSV) with validation', 'Implement rolling baselines and the rule/trend anomaly detector with unit tests', 'Build alert escalation state machine with full audit history', 'Ship the ranked-risk clinician dashboard with drill-down trends', 'Add consent/access controls, synthetic demo dataset and walkthrough video'],
    proofChecklist: ['Anomaly detector unit tests against hand-labelled vitals sequences', 'A demo using only synthetic patient data, stated explicitly', 'Audit log showing every patient-data access in the demo', 'Escalation flow recorded end-to-end (alert → ack timeout → escalation)'],
    testingPlan: ['Unit: baseline math and threshold/trend rules on canned series', 'Unit: escalation state machine transitions incl. timeout paths', 'Integration: ingest → detect → alert → ack flow', 'Negative tests: access without role/consent must be denied and logged'],
    deploymentPlan: ['Deploy behind auth from day one — no anonymous patient views', 'Environment-flagged demo mode that only loads synthetic data', 'Backups + retention policy documented in the README', 'CI: lint + tests; block deploy on failing access-control tests'],
    expectedOutput: 'A ranked, explainable risk view of monitored patients with auditable alerting — replacing scattered spreadsheets and missed deteriorations.',
    prototypeType: 'monitored-cohort dashboard with live alert flow (synthetic data)',
    risks: ['This is decision support, not diagnosis — say so in the UI', 'Alarm fatigue: tune severities or clinicians will ignore alerts', 'Real deployments need regulatory review (e.g. medical-device rules) — out of MVP scope'],
    sensitivity: ['Patient data is highly sensitive (PHI): synthetic data only for demos, strict RBAC, audit logging, and explicit consent modelling are mandatory.'],
    ip: { appropriate: 'conditional', caution: 'A concrete signal-processing/escalation mechanism with measurable technical effect may merit review; “health dashboard” framing is generic and weak for IP.' },
  }),

  cybersecurity: p({
    key: 'cybersecurity',
    label: 'Cybersecurity / Threat Intelligence',
    match: ['security', 'cyber', 'threat', 'cve', 'vulnerability', 'vulnerabilities', 'infosec', 'malware', 'phishing', 'soc ', 'intrusion', 'threat intelligence'],
    subdomains: ['vulnerability prioritisation', 'threat-intel aggregation', 'phishing triage', 'attack-surface monitoring'],
    targetUsers: ['security engineers at small teams without a SOC', 'DevOps engineers who own patching', 'IT admins at colleges/SMBs'],
    mechanisms: [
      { name: 'stack-aware vulnerability scoring pipeline', summary: 'Joins live CVE feeds against a fingerprint of the user’s actual stack (dependencies, services, versions) and computes a deterministic, explainable priority score per finding.' },
      { name: 'threat-intel correlation engine', summary: 'Normalises indicators from multiple feeds into one schema, deduplicates by indicator hash, and correlates across feeds to raise confidence.' },
      { name: 'event-driven alerting system', summary: 'Watches for new high-priority matches and emits routed alerts with the evidence chain (feed → indicator → asset → score).' },
    ],
    modules: ['Feed connector layer (NVD CVE API + advisories) with caching and timeouts', 'Stack fingerprint module (parse lockfiles / service inventory)', 'Match + priority scoring engine (severity × exposure × exploit signals)', 'Evidence-chain explainer (why this finding ranks here)', 'Alert routing with acknowledgement state', 'Trend view: exposure over time per asset group'],
    architecture: ['Scheduled fetchers pull feeds → normaliser → indicator store', 'Fingerprint service maintains the asset/dependency inventory', 'Join engine matches indicators to assets; scoring is pure and table-driven', 'Alert service persists state; dashboard reads ranked findings', 'All external fetches: fixed allow-listed origins, timeout, size caps'],
    techStack: ['Node.js (Express) backend with scheduled fetch jobs', 'React dashboard with ranked findings table', 'MongoDB for indicators, assets, findings, alerts', 'NVD CVE API client (free, keyless or keyed)', 'Hash-based dedupe utilities'],
    dataSources: ['NVD CVE API (free)', 'GitHub Security Advisories (public)', 'Project lockfiles / SBOM exports supplied by the user'],
    databaseModels: ['assets(id, name, kind, stackFingerprint)', 'indicators(id, source, cveId, severity, publishedAt, raw_hash)', 'findings(id, assetId, indicatorId, priorityScore, scoreBreakdown, state)', 'alerts(id, findingId, channel, state, stateHistory[])'],
    skills: ['security data modelling (CVE/CPE basics)', 'feed ingestion with caching and backoff', 'deterministic risk scoring design', 'evidence-chain UX', 'safe handling of untrusted external content'],
    milestones: ['Build the NVD connector with caching + the indicator normaliser', 'Implement stack fingerprinting from a lockfile/SBOM upload', 'Ship the join + priority scoring engine with a written scoring spec', 'Build the ranked findings dashboard with evidence-chain drill-down', 'Add alert routing, trend view, seeded demo and walkthrough'],
    proofChecklist: ['Scoring spec document + unit tests mapping inputs to scores', 'A reproducible demo against a pinned CVE snapshot', 'Evidence chain visible for every ranked finding', 'Repo + demo video showing a new CVE flowing to a routed alert'],
    testingPlan: ['Unit: normaliser against recorded NVD fixtures (no live network in tests)', 'Unit: priority scoring table-driven cases', 'Integration: fixture feed → match → finding → alert', 'Security tests: external content is sanitised before render'],
    deploymentPlan: ['Scheduled fetch job (cron/queue) separate from the API process', 'Pin and document feed API versions', 'Rate-limit and cache feed calls; degrade to cached snapshot on failure', 'CI: lint + tests + a fixture-based end-to-end scoring run'],
    expectedOutput: 'A ranked, explainable “patch this first” list tied to the user’s real stack — instead of an undifferentiated CVE firehose.',
    prototypeType: 'live-feed dashboard with deterministic prioritisation (fixture-reproducible)',
    risks: ['Feed schemas change — isolate normalisers per source', 'False prioritisation erodes trust — keep the score breakdown visible', 'Never auto-execute remediation in the MVP'],
    sensitivity: ['Asset inventories and vulnerability findings are sensitive: private by default, no public demo with real org data.'],
    ip: { appropriate: 'conditional', caution: 'The stack-aware joining/scoring step is the only defensible technical contribution; a CVE dashboard alone is well-trodden prior art.' },
  }),

  education: p({
    key: 'education',
    label: 'Education / College Systems',
    match: ['education', 'college', 'student', 'attendance', 'exam', 'campus', 'faculty', 'classroom', 'course', 'edtech', 'school', 'university', 'learning'],
    subdomains: ['attendance automation', 'academic analytics', 'campus operations', 'collaboration/project systems'],
    targetUsers: ['faculty handling large class sections', 'college administrators', 'students tracking their own standing', 'department coordinators'],
    mechanisms: [
      { name: 'attendance verification pipeline', summary: 'Captures presence events (QR rotation, roll-call, or CV check-in), validates them against session windows and anti-proxy rules, and produces an auditable per-session attendance ledger.' },
      { name: 'academic risk scoring engine', summary: 'Computes explainable at-risk scores from attendance, submission and assessment trends with per-factor breakdowns faculty can defend.' },
      { name: 'computer vision inference pipeline', summary: 'Runs face/ID verification at check-in on-device or server-side, storing only verification outcomes and embeddings policy-compliantly — never raw images by default.' },
    ],
    modules: ['Session and roster management (sections, schedules, enrolment)', 'Presence capture module (rotating QR / device check-in / optional CV verify)', 'Anti-proxy validation rules (session window, device binding, duplicate detection)', 'Attendance ledger with correction workflow and audit trail', 'Shortage alerts and at-risk analytics for faculty', 'Student self-view with dispute/appeal flow'],
    architecture: ['Roster + session services own scheduling state', 'Capture endpoints validate events against active-session rules before writing', 'Ledger is append-only; corrections are new events, never edits', 'Analytics jobs derive aggregates from the ledger', 'Role-gated views: student / faculty / admin see different projections'],
    techStack: ['React (student + faculty portals)', 'Node.js (Express) APIs', 'MongoDB ledger + aggregates', 'QR generation with rotating tokens (TOTP-style)', 'Optional: on-device face verification via a browser ML runtime'],
    dataSources: ['Institution roster CSV import', 'Self-generated presence events', 'Academic calendar (manual or import)'],
    databaseModels: ['sections(id, course, facultyId, schedule)', 'enrolments(sectionId, studentId, status)', 'sessions(id, sectionId, window, qrSeed)', 'presence_events(id, sessionId, studentId, method, validations[], at)', 'attendance_ledger(sessionId, studentId, status, eventRefs[], corrections[])'],
    skills: ['append-only ledger design', 'token rotation / anti-replay basics', 'role-based portals', 'explainable scoring', 'privacy-aware handling of student data'],
    milestones: ['Model sections/sessions/enrolments and build roster import', 'Implement rotating-QR presence capture with anti-proxy validations', 'Build the append-only attendance ledger with correction workflow', 'Ship faculty shortage alerts and the explainable at-risk view', 'Add student self-view + appeals, seed demo data, record walkthrough'],
    proofChecklist: ['Anti-proxy tests: replayed/expired QR events are rejected', 'Ledger audit: every status traces to immutable events', 'A faculty demo showing shortage alert → correction → resolved trail', 'Repo + demo video of a full session lifecycle'],
    testingPlan: ['Unit: QR token rotation and expiry validation', 'Unit: ledger derivation and correction semantics', 'Integration: session open → check-ins → close → aggregates', 'Negative: cross-section check-in and duplicate-device events rejected'],
    deploymentPlan: ['Single deploy with role-gated routes (reuses existing auth patterns)', 'Demo mode seeds an anonymised roster', 'Document data-retention for presence events', 'CI: lint + tests + a scripted session lifecycle'],
    expectedOutput: 'A tamper-resistant attendance and academic-standing system with an audit trail both faculty and students can trust.',
    prototypeType: 'working multi-role portal over a seeded roster',
    risks: ['Face verification raises consent/bias issues — keep it optional and policy-gated', 'Proxy attendance is adversarial; document which attacks the MVP does and does not stop', 'Institutional adoption needs admin buy-in beyond the tech'],
    sensitivity: ['Student records and any biometric verification are sensitive: consent, minimisation (store outcomes, not images), and role-scoped access are required.'],
    ip: { appropriate: 'conditional', caution: 'Attendance apps are crowded prior art; only a specific verification/anti-proxy mechanism with technical effect is worth IP review.' },
  }),

  agriculture: p({
    key: 'agriculture',
    label: 'Agriculture / Smart Farming',
    match: ['agriculture', 'farming', 'crop', 'farmer', 'soil', 'irrigation', 'harvest', 'pest', 'agri', 'plant disease', 'livestock', 'greenhouse'],
    subdomains: ['crop disease detection', 'irrigation optimisation', 'yield advisory', 'market-linkage tools'],
    targetUsers: ['smallholder farmers with low-end smartphones', 'agri-extension officers', 'farmer-producer organisations', 'agronomy students'],
    mechanisms: [
      { name: 'computer vision inference pipeline', summary: 'Classifies leaf/crop images against a known disease set using a compact on-device or server model, returning class, confidence and visual evidence regions.' },
      { name: 'sensor fusion advisory workflow', summary: 'Fuses weather forecast, soil-moisture readings and crop-stage rules into a single irrigation/spray advisory with the contributing factors listed.' },
      { name: 'explainable recommendation engine', summary: 'Maps detections + local conditions to treatment/agronomy recommendations from a curated rule base, citing the rule that fired.' },
    ],
    modules: ['Image capture + quality gate (blur/lighting checks before inference)', 'Disease classification model wrapper with confidence thresholds', 'Low-confidence fallback to extension-officer review queue', 'Weather + crop-stage advisory engine (rule-based, explainable)', 'Offline-first sync for low-connectivity field use', 'Local-language result rendering'],
    architecture: ['Mobile-web client captures images → quality gate → inference endpoint (or on-device model)', 'Detections persist with image hash, class, confidence, region metadata', 'Advisory engine joins detections with Open-Meteo forecast + crop calendar rules', 'Review queue routes low-confidence cases to humans', 'Sync layer queues writes offline and reconciles on connectivity'],
    techStack: ['React PWA (offline-capable, camera access)', 'Node.js (Express) APIs', 'A compact image model (e.g. MobileNet-class) served behind one endpoint', 'MongoDB for detections, advisories, review queue', 'Open-Meteo client for forecasts (free, keyless)'],
    dataSources: ['PlantVillage public leaf-disease dataset (training/eval)', 'Open-Meteo weather API (free)', 'Curated agronomy rule base (documented sources)'],
    databaseModels: ['farms(id, location, crops[], stage)', 'detections(id, farmId, imageHash, class, confidence, regions, reviewedBy)', 'advisories(id, farmId, type, factors[], recommendation, ruleId, issuedAt)', 'review_queue(detectionId, state, assignee, resolution)'],
    skills: ['practical CV model integration', 'rule-based expert systems', 'offline-first PWA patterns', 'low-bandwidth UX', 'evaluation against a labelled dataset'],
    milestones: ['Stand up the inference endpoint against PlantVillage classes with an eval report', 'Build capture + quality gate + detection persistence', 'Implement the weather + crop-stage advisory rules with cited sources', 'Add the low-confidence human review queue', 'Ship offline sync, local-language output, field-style demo and walkthrough'],
    proofChecklist: ['Held-out eval: per-class precision/recall published in the README', 'A low-confidence case visibly routed to human review', 'Advisory output citing the exact rule and weather inputs used', 'Offline capture demo: airplane-mode capture syncing later'],
    testingPlan: ['Unit: quality gate thresholds and confidence routing', 'Unit: advisory rule engine against canned weather/stage inputs', 'Integration: capture → infer → advise → review path', 'Model eval script pinned to a fixed dataset split'],
    deploymentPlan: ['Serve the model behind one autoscaled endpoint or bundle on-device', 'Cache forecasts per location-day to respect free-tier limits', 'PWA deploy with offline asset caching', 'CI: lint + tests + the pinned model-eval script'],
    expectedOutput: 'A field-usable disease detection + advisory tool that tells a farmer what was detected, how confident it is, and what to do — with humans in the loop when unsure.',
    prototypeType: 'offline-capable PWA with live image inference on a public dataset',
    risks: ['Models trained on clean datasets degrade on real field photos — the quality gate and review queue are load-bearing', 'Bad advisories cause real economic harm; keep recommendations rule-cited and conservative', 'Connectivity assumptions must match rural reality'],
    sensitivity: ['Farm location and yield data can be commercially sensitive; default to private per-farm scoping.'],
    ip: { appropriate: 'conditional', caution: 'CV crop-disease detection has dense prior art; only a specific fusion/quality-gating mechanism with measured effect is review-worthy.' },
  }),

  logistics: p({
    key: 'logistics',
    label: 'Logistics / Supply Chain',
    match: ['logistics', 'supply chain', 'delivery', 'fleet', 'route', 'routing', 'warehouse', 'shipment', 'dispatch', 'last mile', 'inventory', 'transport'],
    subdomains: ['route optimisation', 'fleet tracking', 'warehouse slotting', 'shipment exception management'],
    targetUsers: ['dispatch managers at local delivery firms', 'fleet owners with 5–50 vehicles', 'warehouse supervisors', 'e-commerce ops teams'],
    mechanisms: [
      { name: 'route optimization algorithm', summary: 'Solves capacitated multi-stop routing with a deterministic heuristic (savings/2-opt over a distance matrix), producing routes with explainable cost deltas versus the naive plan.' },
      { name: 'shipment exception detection engine', summary: 'Evaluates tracking events against per-leg SLA windows and emits graded exceptions with the breached constraint attached.' },
      { name: 'telemetry processing module', summary: 'Ingests vehicle pings, snaps them to planned routes and computes live ETA drift deterministically.' },
    ],
    modules: ['Stop/order intake with geocoding and time windows', 'Distance-matrix builder (OSM/OSRM-based, cached)', 'Route optimiser (savings heuristic + 2-opt improvement, seeded)', 'Plan-vs-actual tracker with ETA drift computation', 'Exception engine with SLA rules and graded alerts', 'Dispatcher board: routes, load, exceptions in one view'],
    architecture: ['Intake service normalises stops/orders and geocodes once (cached)', 'Matrix service precomputes pairwise costs; optimiser is a pure function over the matrix', 'Telemetry ingester snaps pings to active routes', 'Exception engine reads tracking + SLA tables, writes exception records', 'Dispatcher UI reads composed route/exception projections'],
    techStack: ['React dispatcher board with map (Leaflet + OSM tiles)', 'Node.js (Express) APIs', 'MongoDB for orders, routes, pings, exceptions', 'OpenStreetMap/OSRM for geometry and distances', 'Seeded heuristic optimiser as a standalone tested module'],
    dataSources: ['OpenStreetMap / OSRM routing data (free)', 'User-supplied order/stop CSVs', 'Self-generated vehicle telemetry (simulated for the MVP demo)'],
    databaseModels: ['orders(id, address, geo, window, load)', 'routes(id, date, vehicleId, stops[], plannedCost, optimiserSeed)', 'pings(vehicleId, geo, at)', 'exceptions(id, routeId, stopId, rule, severity, state)'],
    skills: ['routing heuristics (savings, 2-opt)', 'geospatial data handling', 'SLA rule engines', 'map UX', 'benchmarking optimiser quality'],
    milestones: ['Build order intake + cached geocoding + distance matrix', 'Implement the seeded savings/2-opt optimiser with a benchmark vs naive routes', 'Ship the dispatcher board with planned routes on the map', 'Add telemetry snapping, ETA drift and the SLA exception engine', 'Polish, seeded city-scale demo dataset, recorded walkthrough'],
    proofChecklist: ['Benchmark table: optimiser vs naive ordering on fixed datasets (% distance saved)', 'Determinism proof: same seed + input ⇒ identical routes', 'A demo exception firing from a simulated late ping', 'Repo + demo video of plan → dispatch → exception lifecycle'],
    testingPlan: ['Unit: matrix construction and optimiser on small hand-solvable instances', 'Property test: optimised cost ≤ naive cost on random instances', 'Integration: intake → plan → telemetry → exception', 'Map snapping tests with fixture ping traces'],
    deploymentPlan: ['Self-host OSRM or use a free routing tier with caching', 'Optimisation runs as a job (can be queued) — API stays responsive', 'Tile usage within OSM policy; cache aggressively', 'CI: lint + tests + the optimiser benchmark on a pinned dataset'],
    expectedOutput: 'Dispatch plans that are measurably cheaper than manual ordering, plus live exception visibility — with every saving and alert explainable.',
    prototypeType: 'map-based dispatcher board with benchmarked optimiser',
    risks: ['Real-world constraints (driver breaks, vehicle types) multiply quickly — fix MVP constraint scope', 'Free routing tiers rate-limit; cache or self-host', 'GPS noise needs snapping tolerance tuning'],
    sensitivity: ['Vehicle/driver location traces are personal data in many contexts; scope access and retention.'],
    ip: { appropriate: 'conditional', caution: 'Classical routing heuristics are textbook prior art; only a novel constraint-handling or fusion step with measured effect merits review.' },
  }),

  finance: p({
    key: 'finance',
    label: 'Finance / Fraud Detection',
    match: ['finance', 'fintech', 'fraud', 'payment', 'transaction', 'banking', 'upi', 'credit', 'loan', 'anomalous transactions', 'aml', 'risk scoring'],
    subdomains: ['transaction fraud detection', 'expense anomaly review', 'merchant risk', 'reconciliation tooling'],
    targetUsers: ['risk analysts at small fintechs', 'finance/ops teams reviewing expense claims', 'accountants reconciling statements', 'marketplace trust-and-safety teams'],
    mechanisms: [
      { name: 'anomaly detection pipeline', summary: 'Scores each transaction against per-entity behavioural baselines (amount, frequency, counterparty, time-of-day) using deterministic statistical rules with per-factor contributions.' },
      { name: 'rules + velocity engine', summary: 'Evaluates table-driven rules (velocity counters, blocklists, threshold combos) in a defined order with an evaluable trace per decision.' },
      { name: 'case-review workflow engine', summary: 'Routes flagged transactions through analyst queues with disposition outcomes feeding back into rule/threshold tuning.' },
    ],
    modules: ['Transaction ingestion + normalisation (CSV/API) with idempotency keys', 'Per-entity baseline builder (rolling windows per account/merchant)', 'Scoring engine: statistical anomaly + table-driven rules, fully explainable', 'Velocity counters (sliding-window counts per key)', 'Analyst case queue with dispositions and feedback loop', 'Outcome analytics: precision of flags over time'],
    architecture: ['Ingestion validates and dedupes by idempotency key', 'Baseline jobs maintain rolling stats per entity', 'Scoring is a pure function: (txn, baseline, rules) → score + factor breakdown', 'Flags above threshold open cases; analyst dispositions persist', 'Tuning view compares rule precision from disposition history'],
    techStack: ['Node.js (Express) APIs', 'React analyst console', 'MongoDB for transactions, baselines, cases', 'Table-driven rules stored as data, hot-reloadable', 'Synthetic transaction generator for demos'],
    dataSources: ['Synthetic/public transaction datasets (e.g. PaySim-style) for the MVP', 'User-supplied CSV exports', 'Internal disposition history (the feedback loop)'],
    databaseModels: ['transactions(id, entityId, amount, counterparty, channel, at, idempotencyKey)', 'baselines(entityId, stats, windowDays)', 'rules(id, expr, weight, order, active)', 'scores(txnId, total, factors[], ruleHits[])', 'cases(id, txnId, state, disposition, analystId)'],
    skills: ['behavioural baseline statistics', 'rule-engine design', 'sliding-window counters', 'precision/recall evaluation', 'auditable decision trails'],
    milestones: ['Build ingestion with idempotency + the synthetic data generator', 'Implement baselines and the explainable scoring function with unit tests', 'Add the table-driven rules + velocity engine with an evaluation trace', 'Ship the analyst case queue with dispositions', 'Close the loop: precision dashboard from dispositions, demo, walkthrough'],
    proofChecklist: ['Scoring unit tests with hand-computed factor breakdowns', 'Precision/recall report on a labelled synthetic set', 'A case trace from flag → analyst → disposition → tuning view', 'Determinism: rerunning a batch yields identical scores'],
    testingPlan: ['Unit: baseline math, each rule type, velocity windows', 'Property: score is order-independent for a fixed batch', 'Integration: ingest → score → case → disposition', 'Replay test against a pinned labelled dataset'],
    deploymentPlan: ['Batch + near-real-time scoring paths share the same pure scorer', 'Rules deploy as data with versioning', 'No real PII in demos — synthetic only, stated in README', 'CI: lint + tests + pinned-dataset replay'],
    expectedOutput: 'An explainable flag queue where every fraud score decomposes into named factors and rules — auditable enough to defend to a regulator or professor.',
    prototypeType: 'analyst console over a labelled synthetic transaction stream',
    risks: ['Class imbalance makes naive accuracy meaningless — report precision/recall', 'Overblocking has real cost; thresholds must be tunable', 'Real deployments trigger compliance obligations beyond MVP scope'],
    sensitivity: ['Financial transaction data is sensitive; use synthetic data for demos and document handling expectations for real data.'],
    ip: { appropriate: 'conditional', caution: 'Fraud scoring is dense prior art and risks business-method framing; only a concrete technical mechanism with measured effect merits review.' },
  }),

  iot: p({
    key: 'iot',
    label: 'IoT / Sensor Systems',
    match: ['iot', 'sensor', 'sensors', 'embedded', 'esp32', 'arduino', 'raspberry', 'telemetry', 'device', 'mqtt', 'edge', 'smart home', 'smart meter'],
    subdomains: ['environmental sensing', 'asset condition monitoring', 'smart metering', 'edge alerting'],
    targetUsers: ['facility managers monitoring equipment', 'lab/greenhouse operators', 'hardware-curious student teams', 'building administrators'],
    mechanisms: [
      { name: 'telemetry processing module', summary: 'Ingests device readings over MQTT/HTTP, validates against per-sensor calibration envelopes, downsamples into rollups and flags out-of-envelope behaviour.' },
      { name: 'sensor fusion workflow', summary: 'Combines multiple sensor streams (e.g. temperature + vibration + current) into one condition score with the contributing channels listed.' },
      { name: 'event-driven alerting system', summary: 'Threshold/trend rules over rollups emit alerts with hysteresis to prevent flapping, routed with acknowledgement state.' },
    ],
    modules: ['Device registry with per-sensor calibration metadata', 'Ingestion endpoint (MQTT bridge or HTTP) with schema validation', 'Rollup pipeline (raw → 1-min → 1-hour aggregates)', 'Condition scoring via sensor fusion rules', 'Alert engine with hysteresis and ack state', 'Live dashboard: device health, trends, alert history'],
    architecture: ['Devices (or a simulator) publish readings → ingestion validates + timestamps', 'Raw readings land append-only; rollup jobs derive aggregates', 'Fusion/scoring reads rollups, never raw, for stability', 'Alert engine consumes scores with hysteresis bands', 'Dashboard reads aggregates + alert projections only'],
    techStack: ['Node.js (Express) + an MQTT broker or HTTP ingestion', 'React dashboard with live charts', 'MongoDB time-bucketed collections for rollups', 'A device simulator script (so no hardware is required to demo)', 'Optional ESP32/Arduino firmware sketch for one real sensor'],
    dataSources: ['Self-generated sensor telemetry (simulator + optional one real device)', 'Open-Meteo for ambient-condition context', 'Manufacturer calibration sheets for envelope defaults'],
    databaseModels: ['devices(id, type, location, calibration, status)', 'readings(deviceId, channel, value, at) — append-only', 'rollups(deviceId, channel, bucket, min, max, avg, count)', 'alerts(id, deviceId, rule, severity, state, stateHistory[])'],
    skills: ['ingestion protocol design (MQTT/HTTP)', 'time-series rollups', 'hysteresis-based alerting', 'device simulation for testing', 'basic embedded integration'],
    milestones: ['Build the device registry + validated ingestion + the simulator', 'Implement rollup pipeline with time-bucketed storage', 'Add fusion condition scoring with documented channel weights', 'Ship the alert engine with hysteresis and ack flow', 'Live dashboard, optional real-device integration, demo and walkthrough'],
    proofChecklist: ['Simulator-driven end-to-end demo (no hardware excuse)', 'Hysteresis test: noisy input produces no alert flapping', 'Rollup correctness tests against hand-computed buckets', 'Optional: one real sensor feeding the same pipeline on video'],
    testingPlan: ['Unit: schema validation, rollup math, hysteresis transitions', 'Load: simulator at 100 msg/s sustained without loss', 'Integration: reading → rollup → score → alert → ack', 'Clock-skew tests for late/out-of-order readings'],
    deploymentPlan: ['Broker/ingestion as its own process; API/dashboard separate', 'Retention: raw N days, rollups long-term', 'Device auth via per-device tokens', 'CI: lint + tests + a scripted simulator run'],
    expectedOutput: 'A live condition-monitoring view where every alert traces to specific channels and thresholds — demonstrable end-to-end without owning hardware.',
    prototypeType: 'simulator-backed live telemetry dashboard (hardware optional)',
    risks: ['Out-of-order/late data breaks naive aggregations — handle timestamps explicitly', 'Alert tuning is iterative; expose thresholds as data', 'Real hardware adds supply/firmware risk — keep it optional'],
    sensitivity: ['Location-tagged sensor data can reveal occupancy/behaviour patterns; scope dashboards appropriately.'],
    ip: { appropriate: 'conditional', caution: 'Sensor dashboards are generic; a specific fusion/calibration mechanism with measured effect is the only review-worthy angle.' },
  }),

  environment: p({
    key: 'environment',
    label: 'Environmental / Waste Management',
    match: ['waste', 'garbage', 'recycling', 'environment', 'pollution', 'air quality', 'water quality', 'sustainability', 'emissions', 'segregation', 'landfill', 'smart waste'],
    subdomains: ['smart waste collection', 'segregation compliance', 'air/water quality monitoring', 'recycling marketplaces'],
    targetUsers: ['municipal sanitation supervisors', 'housing-society facility managers', 'campus sustainability cells', 'recycling aggregators'],
    mechanisms: [
      { name: 'fill-level prediction and route trigger engine', summary: 'Estimates bin fill trajectories from reported/sensed levels and historical patterns, triggering collection routes when predicted overflow crosses a threshold — with the prediction inputs shown.' },
      { name: 'computer vision inference pipeline', summary: 'Classifies waste-segregation compliance from geotagged photos (segregated vs mixed) with confidence routing to human verification.' },
      { name: 'route optimization algorithm', summary: 'Orders triggered pickups into efficient collection runs using a savings heuristic over road distances.' },
    ],
    modules: ['Bin/site registry with geolocation and capacity', 'Fill-level intake (citizen reports, optional sensors, collector updates)', 'Overflow prediction engine with per-bin history', 'Collection-route generator over triggered bins', 'Segregation photo-audit module with CV + human verify queue', 'Ward-level analytics: overflow incidents, compliance trends'],
    architecture: ['Registry service owns bins/sites; intake normalises level events', 'Prediction job updates fill trajectories per bin daily/hourly', 'Trigger rules enqueue bins; route generator batches them into runs', 'Photo audits flow capture → CV classify → confidence-routed verify', 'Analytics reads event history, never live state, for trends'],
    techStack: ['React PWA for collectors/citizens + admin dashboard', 'Node.js (Express) APIs', 'MongoDB for bins, level events, routes, audits', 'OpenStreetMap for geometry and route ordering', 'Compact image classifier behind one endpoint for segregation audits'],
    dataSources: ['Citizen/collector reported levels (MVP) with optional sensor upgrade path', 'OpenStreetMap geodata (free)', 'Public municipal ward boundaries where available'],
    databaseModels: ['bins(id, geo, capacity, ward, type)', 'level_events(binId, level, source, at)', 'predictions(binId, trajectory, overflowEta, inputs)', 'collection_runs(id, date, binSequence[], distance)', 'audits(id, binId, imageHash, class, confidence, verifiedBy)'],
    skills: ['trajectory estimation from sparse events', 'geospatial routing', 'crowdsourced data quality handling', 'CV classification with human-in-the-loop', 'civic analytics'],
    milestones: ['Build registry + level intake + per-bin history', 'Implement overflow prediction with visible inputs and ETA', 'Add trigger rules + route generation over OSM distances', 'Ship the segregation photo-audit flow with verify queue', 'Ward analytics, seeded city-ward demo, recorded walkthrough'],
    proofChecklist: ['Prediction backtest: predicted vs actual overflow on seeded history', 'Route demo: triggered bins ordered into one efficient run on the map', 'A photo audit flowing through CV → human verify', 'Repo + walkthrough of report → predict → route → collect'],
    testingPlan: ['Unit: trajectory math on canned level histories', 'Unit: trigger thresholds and route ordering on fixtures', 'Integration: report → prediction → run generation', 'CV confidence-routing tests with fixture images'],
    deploymentPlan: ['PWA deploy for field roles; admin behind auth', 'Daily prediction job as scheduled task', 'OSM tile/policy compliance with caching', 'CI: lint + tests + a seeded prediction backtest'],
    expectedOutput: 'Collections triggered by predicted overflow instead of fixed schedules, with measurable reductions in overflow incidents on the seeded demo.',
    prototypeType: 'map-based civic ops dashboard with prediction backtest',
    risks: ['Crowdsourced levels are noisy — weight sources and show uncertainty', 'Municipal adoption is process-heavy; design for a single-ward pilot', 'Sensor retrofits are out of MVP scope'],
    sensitivity: ['Geotagged citizen reports can expose reporter identity; strip reporter identifiers from public views.'],
    ip: { appropriate: 'conditional', caution: 'Smart-bin concepts are heavily published; only a specific prediction/trigger mechanism with backtested effect merits review.' },
  }),

  devtools: p({
    key: 'devtools',
    label: 'Developer Tools / Automation',
    match: ['developer', 'devtool', 'cli', 'ci/cd', 'ci ', 'pipeline', 'automation', 'workflow automation', 'code review', 'testing tool', 'devops', 'build', 'deployment tool', 'lint'],
    subdomains: ['CI failure triage', 'code-quality automation', 'environment/setup tooling', 'release automation'],
    targetUsers: ['developers on small teams who own their own CI', 'open-source maintainers', 'platform engineers', 'student dev teams'],
    mechanisms: [
      { name: 'log correlation and root-cause ranking engine', summary: 'Parses CI/build logs into structured failure events, correlates them with diffs/config changes, and ranks likely root causes deterministically with the matching evidence lines attached.' },
      { name: 'deterministic validation engine', summary: 'Runs a table of repo/config checks (structure, scripts, security hygiene) producing a pass/fail report with exact remediation per failure.' },
      { name: 'event-driven automation workflows', summary: 'Watches repo/CI events and executes declared automation steps with full dry-run and audit modes.' },
    ],
    modules: ['Log ingestion + parser library (per-CI-provider adapters)', 'Failure-event normaliser into one schema', 'Correlation engine: failures × recent diffs/config changes', 'Root-cause ranking with evidence-line citations', 'Fix-suggestion knowledge base (rule-cited, no hallucinated commands)', 'CLI + web report views'],
    architecture: ['Adapters convert provider logs into structured failure events', 'Correlator joins events with git metadata (changed files, config deltas)', 'Ranker is a pure scoring function with documented weights', 'Suggestions map ranked causes to a curated rule base', 'CLI and web render the same report JSON'],
    techStack: ['Node.js CLI + Express API', 'React report viewer', 'Log parser adapters as isolated modules with fixtures', 'Git metadata via local git commands (no external API needed)', 'MongoDB or flat JSON storage for report history'],
    dataSources: ['CI logs supplied by the user (GitHub Actions artifacts, local runs)', 'Git history of the analysed repo', 'A curated failure-pattern rule base (versioned in-repo)'],
    databaseModels: ['runs(id, repo, provider, startedAt, status)', 'failure_events(runId, stage, pattern, lines[], hash)', 'correlations(runId, eventHash, changedFiles[], score, factors)', 'suggestions(eventHash, ruleId, remediation, confidence)'],
    skills: ['log parsing and normalisation', 'heuristic ranking design', 'CLI ergonomics', 'fixture-driven testing', 'git plumbing'],
    milestones: ['Build one provider adapter with fixture logs and the event schema', 'Implement diff/config correlation with git metadata', 'Ship root-cause ranking with evidence citations and weight docs', 'Add the rule-cited suggestion base + CLI report', 'Web viewer, second provider adapter, demo repo and walkthrough'],
    proofChecklist: ['Fixture suite: known failure logs map to expected ranked causes', 'A real failing run triaged correctly on video', 'Determinism: same inputs ⇒ identical report JSON', 'Repo + before/after demo of triage time on a sample project'],
    testingPlan: ['Unit: each parser adapter against fixture logs', 'Unit: ranking weights on constructed scenarios', 'Snapshot: full report JSON for pinned fixtures', 'Integration: CLI end-to-end on a sample repo'],
    deploymentPlan: ['Distribute the CLI via npm; API optional', 'No log content leaves the user’s machine in CLI mode (privacy default)', 'Versioned rule base with changelog', 'CI: lint + tests + fixture snapshot suite'],
    expectedOutput: 'A ranked “this is why your build failed” report with cited log lines and a concrete fix — cutting triage from minutes of scrolling to seconds.',
    prototypeType: 'CLI + report viewer proven on fixture and real failing builds',
    risks: ['Log formats drift per provider version — pin fixtures and isolate adapters', 'Wrong root-cause claims destroy trust; always show evidence lines', 'Scope creep into auto-fixing — keep MVP read-only'],
    sensitivity: ['Build logs can leak secrets; redact token-like patterns before any storage or display.'],
    ip: { appropriate: 'conditional', caution: 'Dev tooling is crowded; only a specific correlation/ranking mechanism with measured triage improvement is review-worthy.' },
  }),

  civictech: p({
    key: 'civictech',
    label: 'Public Data / Civic Tech',
    match: ['civic', 'public data', 'government', 'open data', 'citizen', 'municipal', 'rti', 'budget', 'policy', 'grievance', 'city data', 'transparency', 'analytics tool'],
    subdomains: ['budget/spend transparency', 'grievance analytics', 'service-level dashboards', 'open-data explorers'],
    targetUsers: ['journalists investigating public spending', 'RWA/citizen groups', 'policy researchers', 'municipal performance cells'],
    mechanisms: [
      { name: 'multi-source public-data normalisation pipeline', summary: 'Ingests heterogeneous government datasets (CSV/API/PDF tables), normalises entities and time periods into one schema, and tracks per-field provenance.' },
      { name: 'scoring/ranking engine', summary: 'Computes comparable indices (e.g. ward service-level scores) from normalised data with the full formula and inputs published.' },
      { name: 'change-detection and alerting engine', summary: 'Diffs successive dataset releases and surfaces material changes (new spends, deleted records) with provenance.' },
    ],
    modules: ['Dataset connector layer (data.gov-style APIs, CSV drops) with versioned snapshots', 'Entity/period normaliser with provenance tracking', 'Index/score computation engine (published methodology)', 'Release diff engine for change detection', 'Public explorer UI with downloadable evidence', 'Methodology page generated from the actual config'],
    architecture: ['Connectors snapshot raw releases immutably', 'Normaliser maps raw → canonical entities with field-level provenance', 'Index engine is pure: (canonical data, methodology config) → scores', 'Diff engine compares snapshot pairs', 'Explorer serves precomputed views; every number links to its sources'],
    techStack: ['Node.js (Express) ingestion + APIs', 'React public explorer with charts', 'MongoDB for snapshots, canonical records, scores', 'data.gov / Census / WorldBank connectors (free)', 'CSV/PDF-table extraction utilities'],
    dataSources: ['data.gov.in / data.gov open datasets (free)', 'Census and World Bank APIs (free)', 'Municipal CSV/PDF releases supplied or scraped within ToS'],
    databaseModels: ['datasets(id, source, version, fetchedAt, rawHash)', 'canonical_records(datasetId, entity, period, metrics, provenance)', 'indices(entity, period, score, formulaVersion, inputs)', 'release_diffs(datasetA, datasetB, changes[])'],
    skills: ['messy public-data wrangling', 'provenance modelling', 'published-methodology index design', 'data-journalism UX', 'snapshot diffing'],
    milestones: ['Build connectors + immutable snapshotting for two public datasets', 'Implement the entity/period normaliser with provenance', 'Ship the index engine with a generated methodology page', 'Add release diffing and change alerts', 'Public explorer with evidence links, demo and walkthrough'],
    proofChecklist: ['Every displayed number click-throughs to its raw source row', 'Methodology page auto-generated from live config (no drift)', 'A detected real change between two dataset releases', 'Repo + walkthrough from raw release to ranked index'],
    testingPlan: ['Unit: normaliser on fixture rows incl. malformed records', 'Unit: index formula against hand-computed cases', 'Snapshot: explorer view JSON for pinned datasets', 'Diff tests on constructed release pairs'],
    deploymentPlan: ['Scheduled re-fetch with snapshot versioning', 'Static-friendly explorer (precomputed JSON) for cheap hosting', 'Clear data-licence attribution per source', 'CI: lint + tests + pinned-dataset rebuild'],
    expectedOutput: 'A public, provenance-linked index over real government data — where every claim is reproducible from the raw release.',
    prototypeType: 'public explorer over versioned real open datasets',
    risks: ['Public datasets break/move without notice — snapshot everything', 'Methodology disputes are the product; publish formulas openly', 'PDF extraction is brittle; budget time per format'],
    sensitivity: ['Some “public” records contain personal data (names in grievances); minimise and aggregate before publishing.'],
    ip: { appropriate: 'weak', caution: 'Civic dashboards over open data are rarely IP-defensible; treat this as a transparency/portfolio play, not a patent route.' },
  }),

  research: p({
    key: 'research',
    label: 'Research / Academic Analytics',
    match: ['research', 'academic', 'paper', 'papers', 'citation', 'scholar', 'literature', 'arxiv', 'publication', 'thesis', 'systematic review', 'bibliometric'],
    subdomains: ['literature mapping', 'citation analytics', 'lab/department dashboards', 'reproducibility tooling'],
    targetUsers: ['postgraduate students starting literature reviews', 'faculty tracking field movement', 'research-cell coordinators', 'journal-club organisers'],
    mechanisms: [
      { name: 'knowledge graph', summary: 'Builds a typed graph (papers, authors, venues, concepts) from open scholarly APIs and computes structural signals (bridging papers, emerging clusters) deterministically.' },
      { name: 'concept-drift and trend detection engine', summary: 'Tracks term/concept frequency across time-sliced corpora to surface rising and fading research directions with the underlying counts shown.' },
      { name: 'scoring/ranking engine', summary: 'Ranks papers for a query by a published formula over recency, citation velocity and concept overlap — no opaque relevance.' },
    ],
    modules: ['Scholarly API connector layer (OpenAlex, Crossref, arXiv) with caching', 'Graph builder: papers/authors/venues/concepts with typed edges', 'Trend engine over time-sliced concept counts', 'Reading-path generator (ordered papers from foundational to frontier)', 'Lab dashboard: output, venues, collaboration map', 'Export: BibTeX + annotated reading lists'],
    architecture: ['Connectors normalise records into one scholarly schema (cached, rate-limited)', 'Graph store holds typed nodes/edges; metrics jobs compute structural signals', 'Trend engine reads time-sliced aggregates', 'Ranking is a pure published formula over graph + trend features', 'UI renders graph neighbourhoods and generated reading paths'],
    techStack: ['Node.js (Express) APIs with connector caching', 'React + a graph-visualisation library', 'MongoDB for records, edges, aggregates', 'OpenAlex/Crossref/arXiv clients (free)', 'BibTeX export utilities'],
    dataSources: ['OpenAlex API (free)', 'Crossref API (free, polite-pool mailto)', 'arXiv API (free)'],
    databaseModels: ['papers(id, externalIds, title, year, venue, concepts[])', 'authors(id, name, affiliations[])', 'edges(from, to, type, weight)', 'concept_counts(concept, yearSlice, count)', 'reading_paths(query, orderedPaperIds[], rationale)'],
    skills: ['scholarly API integration', 'graph modelling and metrics', 'trend analysis over corpora', 'ranking-formula design', 'research UX'],
    milestones: ['Build the three connectors with caching and the unified schema', 'Construct the typed graph and basic structural metrics', 'Implement the trend engine with time-sliced counts', 'Ship query → ranked papers → generated reading path', 'Lab dashboard, BibTeX export, seeded field demo and walkthrough'],
    proofChecklist: ['Ranking formula published and unit-tested against hand cases', 'A generated reading path validated by a faculty member (testimonial)', 'Trend chart reproducible from cached raw counts', 'Repo + demo from query to exported reading list'],
    testingPlan: ['Unit: connector normalisers on recorded API fixtures', 'Unit: graph metrics on small hand-checkable graphs', 'Unit: ranking formula cases', 'Integration: query → graph → path on a pinned fixture corpus'],
    deploymentPlan: ['Respect API rate limits with caching + mailto identification', 'Nightly refresh job for followed fields', 'Static export mode for sharing a field map', 'CI: lint + tests + fixture-corpus rebuild'],
    expectedOutput: 'A defensible, reproducible map of a research field with an ordered reading path — replacing weeks of ad-hoc Googling.',
    prototypeType: 'interactive field map over live open scholarly APIs',
    risks: ['Scholarly metadata is noisy (author disambiguation) — scope to IDs where available', 'Citation lag biases trend signals; show counts, not just trends', 'Graph viz performance needs node-count caps'],
    sensitivity: ['Author-level analytics can be misread as performance evaluation; frame outputs as field maps, not people rankings.'],
    ip: { appropriate: 'weak', caution: 'Bibliometric tooling is heavily published; treat as research-infrastructure/portfolio value rather than a patent route.' },
  }),

  aiml: p({
    key: 'aiml',
    label: 'AI/ML Systems',
    match: ['ai ', 'machine learning', 'ml ', 'model', 'llm', 'nlp', 'computer vision', 'deep learning', 'neural', 'recommendation', 'classifier', 'genai', 'rag', 'embedding'],
    subdomains: ['applied classification/detection', 'retrieval-augmented systems', 'recommendation systems', 'ML evaluation tooling'],
    targetUsers: ['students proving applied-ML skill', 'small teams adding one ML capability to a product', 'ML beginners needing evaluation discipline', 'domain experts without ML backgrounds'],
    mechanisms: [
      { name: 'evaluation-first inference pipeline', summary: 'Wraps a task model behind a pipeline that always carries a pinned eval set, confidence thresholds, and a fallback path — predictions ship with metrics, not vibes.' },
      { name: 'explainable recommendation engine', summary: 'Combines deterministic feature scoring with optional learned re-ranking, exposing per-item factor contributions.' },
      { name: 'retrieval + grounding pipeline', summary: 'Embeds and indexes a domain corpus, retrieves evidence for each query, and constrains generation to cited retrieved content with a keyword fallback when embeddings are unavailable.' },
    ],
    modules: ['Dataset module: pinned splits, versioned, with a datasheet', 'Model wrapper with confidence thresholds and a deterministic fallback', 'Evaluation harness: metrics per class/slice, regression-gated', 'Inference API with input validation and rate limits', 'Feedback capture: user corrections feed the next eval round', 'Model card / limitations page generated from real eval output'],
    architecture: ['Data layer owns immutable splits and versions', 'Training/fitting is scripted and reproducible (seeded)', 'Serving wraps the model with thresholds + fallback rules', 'Eval harness runs on every change; metrics persist per version', 'Feedback loop stores corrections for the next iteration — never silently retrains'],
    techStack: ['Python or JS model layer (task-appropriate) behind one HTTP endpoint', 'Node.js (Express) application APIs', 'React UI showing prediction + confidence + evidence', 'MongoDB for predictions, feedback, eval runs', 'Pinned public dataset for the chosen task'],
    dataSources: ['A pinned public dataset for the chosen task (documented licence)', 'User feedback/corrections collected by the app', 'Optional domain corpus for retrieval grounding'],
    databaseModels: ['datasets(version, split, checksum, datasheet)', 'eval_runs(modelVersion, metrics, sliceMetrics, at)', 'predictions(id, input_hash, output, confidence, modelVersion)', 'feedback(predictionId, correction, userId, at)'],
    skills: ['dataset discipline and datasheets', 'evaluation design (per-slice metrics)', 'serving with thresholds/fallbacks', 'reproducible training scripts', 'honest model-card writing'],
    milestones: ['Pin the dataset, write the datasheet, build versioned splits', 'Train/fit the baseline with a seeded reproducible script', 'Build the eval harness with per-slice metrics and regression gates', 'Serve behind thresholds + fallback with the evidence-showing UI', 'Feedback loop, model card, demo and walkthrough'],
    proofChecklist: ['Eval report with per-class/per-slice metrics in the README', 'Reproducibility: documented command regenerates the reported metrics', 'A low-confidence input visibly taking the fallback path', 'Model card stating limitations honestly'],
    testingPlan: ['Unit: data pipeline determinism (checksum-pinned splits)', 'Eval regression gate in CI against pinned metrics', 'API tests: validation, thresholds, fallback routing', 'Drift check comparing live input stats to training stats'],
    deploymentPlan: ['Model behind one autoscaled endpoint; app server separate', 'Versioned model artifacts; instant rollback path', 'Eval gate blocks deploys on metric regression', 'CI: lint + tests + the eval harness'],
    expectedOutput: 'An ML feature that ships with its own evidence — pinned metrics, confidence-gated predictions, and a fallback — instead of an undocumented demo model.',
    prototypeType: 'served model with public eval report and confidence-gated UI',
    risks: ['Eval-set leakage invalidates every claim — pin and checksum splits', 'Demos overfit to happy paths; per-slice metrics expose this', 'Compute cost: choose model scale to fit free/student budgets'],
    sensitivity: ['Training/feedback data may contain personal information; document collection, consent and retention in the datasheet.'],
    ip: { appropriate: 'conditional', caution: 'Generic “AI recommendation” framing is weak (and Section 3(k)-exposed); only a specific technical mechanism with measured effect merits review.' },
  }),

  marketplace: p({
    key: 'marketplace',
    label: 'Marketplace / Collaboration Systems',
    match: ['marketplace', 'collaboration', 'matching', 'platform', 'community platform', 'gig', 'freelance', 'team formation', 'peer', 'exchange', 'booking', 'listing'],
    subdomains: ['skill/team matching', 'two-sided service marketplaces', 'resource-sharing platforms', 'project collaboration hubs'],
    targetUsers: ['students forming project teams', 'campus communities sharing resources', 'local service providers and seekers', 'club/society coordinators'],
    mechanisms: [
      { name: 'explainable matching and ranking engine', summary: 'Scores candidate matches on declared skills, availability overlap, history and reciprocity with per-factor contributions shown to both sides.' },
      { name: 'reputation and verification workflow', summary: 'Builds trust scores from verified events (completed engagements, mutual confirmations) rather than free-text reviews, with dispute states.' },
      { name: 'deterministic validation engine', summary: 'Gates listings/profiles through completeness and policy checks before they enter matching.' },
    ],
    modules: ['Profile + listing management with structured skill/need taxonomies', 'Matching engine with published factor weights', 'Availability/overlap computation', 'Engagement lifecycle (proposed → active → completed → confirmed)', 'Verified-event reputation with dispute workflow', 'Discovery UI with explainable match reasons'],
    architecture: ['Profiles/listings validated by the gate before indexing', 'Matching is a pure scoring function over indexed structured fields', 'Engagement state machine owns lifecycle transitions', 'Reputation derives only from confirmed lifecycle events', 'Discovery reads ranked matches with factor breakdowns'],
    techStack: ['React (discovery + profile UIs)', 'Node.js (Express) APIs', 'MongoDB for profiles, listings, engagements, reputation events', 'Structured taxonomy data (skills/needs) versioned in-repo', 'Notification layer for lifecycle events'],
    dataSources: ['User-declared structured profiles (the platform’s own data)', 'Institution roster import for campus deployments', 'Optional GitHub profile verification for skill evidence'],
    databaseModels: ['profiles(id, skills[], needs[], availability, verifications[])', 'listings(id, ownerId, type, taxonomyTags[], state)', 'matches(listingId, candidateId, score, factors[])', 'engagements(id, parties[], state, stateHistory[])', 'reputation_events(profileId, engagementId, kind, at)'],
    skills: ['matching-algorithm design', 'state-machine lifecycles', 'trust/reputation modelling', 'two-sided UX', 'taxonomy design'],
    milestones: ['Build structured profiles/listings with the validation gate', 'Implement the explainable matching engine with weight docs', 'Ship the engagement lifecycle state machine', 'Add verified-event reputation with disputes', 'Discovery UI with match explanations, seeded demo, walkthrough'],
    proofChecklist: ['Matching unit tests with hand-computed factor scores', 'A full engagement lifecycle recorded end-to-end', 'Reputation provably derived only from confirmed events', 'Repo + demo of match reason transparency on both sides'],
    testingPlan: ['Unit: matching factors and weights on fixtures', 'Unit: lifecycle state machine incl. dispute paths', 'Integration: listing → match → engagement → reputation', 'Abuse tests: self-confirmation and duplicate-profile attempts rejected'],
    deploymentPlan: ['Single deploy with role-based views', 'Seeded demo community for evaluation', 'Moderation/reporting hooks from day one', 'CI: lint + tests + lifecycle integration run'],
    expectedOutput: 'Matches both sides can trust because every score decomposes into visible factors and reputation comes only from verified outcomes.',
    prototypeType: 'two-sided platform demo over a seeded community',
    risks: ['Cold-start: matching is useless without seeded supply — plan the seed strategy', 'Reputation gaming is adversarial; verified events mitigate but don’t eliminate it', 'Moderation load grows with openness'],
    sensitivity: ['Profiles contain personal data; minimise public exposure and support deletion.'],
    ip: { appropriate: 'weak', caution: 'Marketplace/matching ideas read as business methods (India Section 3(k) exposure); IP-readiness should stay conservative regardless of traction.' },
  }),
};

/* Generic profile — used only when no domain matches; intentionally marked so
   validators can detect over-reliance on it. */
export const GENERIC_PROFILE = p({
  key: 'generic',
  label: 'General Software',
  match: [],
  subdomains: ['general workflow tooling'],
  targetUsers: ['a clearly named primary user group (refine this — generic targets weaken the idea)'],
  mechanisms: [
    { name: 'scoring/ranking engine', summary: 'Collects the relevant signals, applies a documented deterministic scoring formula, and returns ranked results with per-factor explanations.' },
    { name: 'deterministic validation engine', summary: 'Runs a table of domain checks over inputs and produces a pass/fail report with exact remediation per failure.' },
  ],
  modules: ['Signal/data intake with validation', 'Deterministic scoring or rules core', 'Explainable results view', 'Feedback capture loop'],
  architecture: ['Intake API normalises inputs', 'Pure scoring/rules core', 'Results service with explanations', 'Feedback store for iteration'],
  techStack: ['React frontend', 'Node.js (Express) backend', 'MongoDB'],
  dataSources: ['User-supplied data (define a concrete source before building)'],
  databaseModels: ['inputs(id, payload, at)', 'results(id, inputId, score, factors[])', 'feedback(resultId, outcome, at)'],
  skills: ['REST API design', 'deterministic scoring', 'frontend development', 'testing'],
  milestones: ['Define the concrete data source and schema', 'Build intake + the scoring/rules core with tests', 'Ship the explainable results view', 'Add feedback capture, demo data and walkthrough'],
  proofChecklist: ['Public repo with meaningful commits', 'Scoring unit tests', 'A recorded demo of the full flow'],
  testingPlan: ['Unit tests for the core logic', 'One end-to-end integration test'],
  deploymentPlan: ['Dockerised deploy to a managed host with CI (lint + test + build)'],
  expectedOutput: 'A working tool with an explainable core — but the idea needs domain grounding to be competitive.',
  prototypeType: 'working web prototype',
  risks: ['Without domain grounding this remains a generic tool — sharpen the domain before investing heavily'],
  sensitivity: [],
  ip: { appropriate: 'weak', caution: 'Generic software workflows are not IP-defensible; establish a concrete technical differentiation before any IP analysis.' },
});

export const PROFILE_KEYS = Object.keys(DOMAIN_PROFILES);

export function getProfile(key) {
  return DOMAIN_PROFILES[key] || GENERIC_PROFILE;
}

/* Lines that mark output as generic-profile-derived; quality validators use
   this to detect blueprint-only / boilerplate output. */
export const GENERIC_MARKER_LINES = new Set([
  ...GENERIC_PROFILE.modules,
  ...GENERIC_PROFILE.architecture,
  ...GENERIC_PROFILE.milestones,
]);

export default { DOMAIN_PROFILES, GENERIC_PROFILE, PROFILE_KEYS, getProfile, GENERIC_MARKER_LINES };
